import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Navigate, NavLink, Route, Routes, useNavigate } from 'react-router-dom';
import {
  createUserWithEmailAndPassword, onAuthStateChanged, sendPasswordResetEmail,
  signInWithEmailAndPassword, signInWithPopup, signOut, updateProfile, User,
} from 'firebase/auth';
import { doc, getDoc, serverTimestamp, setDoc } from 'firebase/firestore';
import { BookOpen, BrainCircuit, ChartNoAxesCombined, Headphones, Home as HomeIcon, Languages, LogOut, MessageCircleMore, Mic, Settings, Sparkles, Target, UserRound, Volume2 } from 'lucide-react';
import { auth, db, googleProvider, isFirebaseConfigured } from './firebase';

type Profile = { displayName:string; interfaceLanguage:string; nativeLanguage:string; learningGoal:string; cefrLevel:string; dailyTargetMinutes:number; onboardingCompleted:boolean };
const defaultProfile: Profile = { displayName:'Learner', interfaceLanguage:'English', nativeLanguage:'Arabic', learningGoal:'Daily conversation', cefrLevel:'A1', dailyTargetMinutes:15, onboardingCompleted:false };

const curriculum = [
  {id:'u1',title:'Introductions',icon:'👋',lessons:['Hello & goodbye','My name is…','Countries & nationalities','Be: am / is / are']},
  {id:'u2',title:'Everyday Life',icon:'☀️',lessons:['Daily routines','Telling the time','Present simple','Frequency words']},
  {id:'u3',title:'Family & People',icon:'👥',lessons:['Family words','Describe people','Possessives','Have / has']},
  {id:'u4',title:'Food & Drinks',icon:'☕',lessons:['Food vocabulary','Ordering politely','Countable nouns','Some / any']},
  {id:'u5',title:'Places & Directions',icon:'🗺️',lessons:['Places in town','Ask for directions','There is / are','Prepositions']},
  {id:'u6',title:'Work & Study',icon:'💼',lessons:['Jobs','Study life','Can / can’t','Simple requests']},
];

function Robot({small=false}:{small?:boolean}) { return <div className={`robot ${small?'small':''}`} aria-label="English Twin AI"><div className="antenna"/><div className="robot-face"><span/><span/><i/></div><div className="robot-body">ET</div></div> }

function useSession(){
  const [user,setUser]=useState<User|null>(null); const [profile,setProfile]=useState<Profile|null>(null); const [loading,setLoading]=useState(true);
  useEffect(()=>onAuthStateChanged(auth, async u=>{setUser(u); if(u){const snap=await getDoc(doc(db,'users',u.uid)); setProfile(snap.exists()? snap.data() as Profile : {...defaultProfile,displayName:u.displayName||u.email?.split('@')[0]||'Learner'});} else setProfile(null); setLoading(false)}),[]);
  const save=async(p:Profile)=>{if(!user)return; await setDoc(doc(db,'users',user.uid),{...p,email:user.email,uid:user.uid,updatedAt:serverTimestamp()},{merge:true}); setProfile(p)};
  return {user,profile,loading,save};
}

function Auth(){ const nav=useNavigate(); const [mode,setMode]=useState<'login'|'register'>('login'); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [name,setName]=useState(''); const [error,setError]=useState('');
  async function submit(e:FormEvent){e.preventDefault();setError('');try{if(mode==='register'){const c=await createUserWithEmailAndPassword(auth,email,password); if(name) await updateProfile(c.user,{displayName:name}); await setDoc(doc(db,'users',c.user.uid),{...defaultProfile,displayName:name||email.split('@')[0],email,uid:c.user.uid,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});}else await signInWithEmailAndPassword(auth,email,password);nav('/');}catch(e:any){setError(e.message?.replace('Firebase: ','')||'Authentication failed')}}
  if(!isFirebaseConfigured) return <main className="center"><section className="auth-card"><Robot/><h1>English Twin</h1><p>Firebase configuration is required once before real sign-in can run.</p><code>Add VITE_FIREBASE_* variables from .env.example</code></section></main>;
  return <main className="center"><section className="auth-card"><Robot/><div><span className="eyebrow">AI LANGUAGE COACH</span><h1>English Twin</h1><p>Learn naturally. Speak confidently. Your AI coach remembers how you learn.</p></div><div className="seg"><button className={mode==='login'?'active':''} onClick={()=>setMode('login')}>Sign in</button><button className={mode==='register'?'active':''} onClick={()=>setMode('register')}>Create account</button></div><form onSubmit={submit}>{mode==='register'&&<input placeholder="Your name" value={name} onChange={e=>setName(e.target.value)} required/>}<input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Password" minLength={6} value={password} onChange={e=>setPassword(e.target.value)} required/>{error&&<p className="error">{error}</p>}<button className="primary" type="submit">{mode==='login'?'Sign in':'Create account'}</button></form><button className="google" onClick={async()=>{setError('');try{await signInWithPopup(auth,googleProvider);nav('/')}catch(e:any){setError(e.message||'Google sign-in failed')}}}>Continue with Google</button>{mode==='login'&&<button className="text" onClick={async()=>{if(!email)return setError('Enter your email first'); await sendPasswordResetEmail(auth,email); setError('Password reset email sent.')}}>Forgot password?</button>}</section></main> }

function Onboarding({profile,save}:{profile:Profile;save:(p:Profile)=>Promise<void>}){const [p,setP]=useState(profile);const [step,setStep]=useState(0); const steps=[<><h2>What is your main goal?</h2>{['Daily conversation','Work','Travel','Study','Moving abroad'].map(x=><Choice key={x} on={()=>setP({...p,learningGoal:x})} active={p.learningGoal===x}>{x}</Choice>)}</>,<><h2>What is your English level?</h2>{['A1','A2','B1','B2','C1'].map(x=><Choice key={x} on={()=>setP({...p,cefrLevel:x})} active={p.cefrLevel===x}>{x}</Choice>)}</>,<><h2>Daily practice target</h2>{[5,10,15,20,30].map(x=><Choice key={x} on={()=>setP({...p,dailyTargetMinutes:x})} active={p.dailyTargetMinutes===x}>{x} minutes</Choice>)}</>];return <main className="center"><section className="onboard"><Robot/><span className="eyebrow">SET UP YOUR ENGLISH TWIN</span>{steps[step]}<div className="row"><button className="secondary" disabled={!step} onClick={()=>setStep(step-1)}>Back</button><button className="primary" onClick={async()=>step<steps.length-1?setStep(step+1):save({...p,onboardingCompleted:true})}>{step<steps.length-1?'Continue':'Start learning'}</button></div></section></main>}
function Choice({children,active,on}:{children:any;active:boolean;on:()=>void}){return <button className={`choice ${active?'active':''}`} onClick={on}>{children}<span>{active?'✓':'›'}</span></button>}

function Shell({profile}:{profile:Profile}){return <div className="app-shell"><div className="phone"><Routes><Route path="/" element={<Home profile={profile}/>}/><Route path="/learn" element={<Learn/>}/><Route path="/speak" element={<Speak/>}/><Route path="/progress" element={<Progress profile={profile}/>}/><Route path="/profile" element={<ProfilePage profile={profile}/>}/></Routes><nav>{[['/',HomeIcon,'Home'],['/learn',BookOpen,'Learn'],['/speak',Mic,'Speak'],['/progress',ChartNoAxesCombined,'Progress'],['/profile',UserRound,'Profile']].map(([to,I,label]:any)=><NavLink end={to==='/'} key={to} to={to}><I/><small>{label}</small></NavLink>)}</nav></div></div>}
function Home({profile}:{profile:Profile}){return <Page><header><div><span className="eyebrow">GOOD EVENING</span><h1>{profile.displayName} 👋</h1><p>Ready for a focused English session?</p></div><button className="icon"><Settings/></button></header><section className="hero"><div><span className="eyebrow">YOUR ENGLISH TWIN</span><h2>Let’s train your speaking confidence today.</h2><button className="primary"><Mic/> Start talking</button></div><Robot small/></section><section><Title icon={<BrainCircuit/>}>Learning engine</Title><div className="empty-engine"><Sparkles/><div><b>Personalization activates as you learn</b><p>Your Twin will turn real lesson results into smart practice.</p></div></div></section><section><Title icon={<Target/>}>Today’s mission</Title><div className="mission"><div className="mission-art">☕</div><div><b>Real-life conversation</b><h3>Ordering coffee naturally</h3><small>8 min · A1 · Speaking</small></div><button>Start</button></div></section><section><Title icon={<Sparkles/>}>AI insight</Title><div className="insight">Complete your first lessons and your Twin will detect patterns in vocabulary, grammar and fluency.</div></section></Page>}
function Learn(){return <Page><header><div><span className="eyebrow">CEFR ROADMAP</span><h1>Learn</h1><p>A real path from foundations to fluent communication.</p></div></header><div className="levelbar"><b>A1 · Foundations</b><span>6 units</span></div>{curriculum.map((u,i)=><section className="unit" key={u.id}><div className="unit-head"><div className="unit-icon">{u.icon}</div><div><span>UNIT {i+1}</span><h3>{u.title}</h3></div></div><div className="lesson-list">{u.lessons.map((l,j)=><button key={l}><span className="lesson-index">{j+1}</span><div><b>{l}</b><small>{j%2?'Practice + review':'Learn + practice'}</small></div><span>›</span></button>)}</div></section>)}</Page>}
function Speak(){const [state,setState]=useState<'ready'|'listening'>('ready');return <Page><header><div><span className="eyebrow">VOICE LAB</span><h1>Speak</h1><p>Practice real English with your AI Twin.</p></div></header><section className="speak-card"><Robot/><span className={`live ${state}`}>{state==='ready'?'READY':'LISTENING…'}</span><h2>{state==='ready'?'Tell me about your day':'I’m listening'}</h2><p>Speak naturally. Your Twin will help with clarity, grammar and better phrasing.</p><button className="mic" onClick={()=>setState(state==='ready'?'listening':'ready')}><Mic/></button><small>{state==='ready'?'Tap to start speaking':'Tap to stop'}</small></section><div className="quick"><button><MessageCircleMore/> Daily conversation</button><button><Volume2/> Pronunciation</button><button><Headphones/> Listening reply</button></div></Page>}
function Progress({profile}:{profile:Profile}){return <Page><header><div><span className="eyebrow">YOUR JOURNEY</span><h1>Progress</h1><p>Real growth, based on completed learning activity.</p></div></header><section className="level-card"><div className="badge">{profile.cefrLevel}</div><div><span>Current level</span><h2>{profile.cefrLevel} Foundations</h2><p>Progress data appears as lessons are completed.</p></div></section><section><Title icon={<ChartNoAxesCombined/>}>Skill growth</Title><div className="chart-empty"><BrainCircuit/><b>No fake scores here.</b><p>Speaking, listening, grammar and vocabulary charts unlock from your real results.</p></div></section></Page>}
function ProfilePage({profile}:{profile:Profile}){return <Page><header><div><span className="eyebrow">ACCOUNT</span><h1>Profile</h1></div></header><section className="profile-card"><Robot small/><h2>{profile.displayName}</h2><span className="pill">{profile.cefrLevel} · {profile.learningGoal}</span></section><div className="settings-list"><button><Languages/><div><b>Interface language</b><small>{profile.interfaceLanguage}</small></div><span>›</span></button><button><Target/><div><b>Daily target</b><small>{profile.dailyTargetMinutes} minutes</small></div><span>›</span></button><button><Settings/><div><b>Preferences</b><small>Audio, notifications, privacy</small></div><span>›</span></button><button className="danger" onClick={()=>signOut(auth)}><LogOut/><div><b>Sign out</b></div></button></div></Page>}
function Title({children,icon}:{children:any;icon:any}){return <div className="section-title"><span>{icon}</span><h3>{children}</h3></div>}; function Page({children}:{children:any}){return <main className="page">{children}</main>}
export default function App(){const {user,profile,loading,save}=useSession(); if(loading)return <main className="center"><Robot/><p>Waking your English Twin…</p></main>; if(!user)return <Routes><Route path="*" element={<Auth/>}/></Routes>; if(!profile||!profile.onboardingCompleted)return <Onboarding profile={profile||defaultProfile} save={save}/>; return <Shell profile={profile}/>}
