import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Navigate, NavLink, Route, Routes, useNavigate, useParams } from 'react-router-dom';
import {
  createUserWithEmailAndPassword, onAuthStateChanged, sendPasswordResetEmail,
  signInWithEmailAndPassword, signInWithPopup, signOut, updateProfile, User,
} from 'firebase/auth';
import { doc, getDoc, serverTimestamp, setDoc } from 'firebase/firestore';
import { ArrowLeft, BookOpen, BrainCircuit, ChartNoAxesCombined, CheckCircle2, Headphones, Home as HomeIcon, Languages, LogOut, MessageCircleMore, Mic, Settings, Sparkles, Target, UserRound, Volume2, XCircle } from 'lucide-react';
import { auth, db, googleProvider, isFirebaseConfigured } from './firebase';
import { lessonById, lessons, lessonsForUnit, units, Activity } from './curriculum';
import { loadLessonProgress, ProgressMap, saveLessonCompletion, summarizeProgress } from './learning';

type Profile = { displayName:string; interfaceLanguage:string; nativeLanguage:string; learningGoal:string; cefrLevel:string; dailyTargetMinutes:number; onboardingCompleted:boolean };
const defaultProfile: Profile = { displayName:'Learner', interfaceLanguage:'English', nativeLanguage:'Arabic', learningGoal:'Daily conversation', cefrLevel:'A1', dailyTargetMinutes:15, onboardingCompleted:false };

function Robot({small=false}:{small?:boolean}) { return <div className={`robot ${small?'small':''}`} aria-label="English Twin AI"><div className="antenna"/><div className="robot-face"><span/><span/><i/></div><div className="robot-body">ET</div></div> }

function useSession(){
  const [user,setUser]=useState<User|null>(null); const [profile,setProfile]=useState<Profile|null>(null); const [progress,setProgress]=useState<ProgressMap>({}); const [loading,setLoading]=useState(true);
  useEffect(()=>onAuthStateChanged(auth, async u=>{setLoading(true);setUser(u);try{if(u){const [snap,p]=await Promise.all([getDoc(doc(db,'users',u.uid)),loadLessonProgress(u.uid)]); setProfile(snap.exists()? snap.data() as Profile : {...defaultProfile,displayName:u.displayName||u.email?.split('@')[0]||'Learner'});setProgress(p);} else {setProfile(null);setProgress({});}}finally{setLoading(false)}}),[]);
  const save=async(p:Profile)=>{if(!user)return; await setDoc(doc(db,'users',user.uid),{...p,email:user.email,uid:user.uid,updatedAt:serverTimestamp()},{merge:true}); setProfile(p)};
  return {user,profile,progress,setProgress,loading,save};
}

function Auth(){ const nav=useNavigate(); const [mode,setMode]=useState<'login'|'register'>('login'); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [name,setName]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  async function submit(e:FormEvent){e.preventDefault();setError('');setBusy(true);try{if(mode==='register'){const c=await createUserWithEmailAndPassword(auth,email,password); if(name) await updateProfile(c.user,{displayName:name}); await setDoc(doc(db,'users',c.user.uid),{...defaultProfile,displayName:name||email.split('@')[0],email,uid:c.user.uid,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});}else await signInWithEmailAndPassword(auth,email,password);nav('/');}catch(e:any){setError(e.message?.replace('Firebase: ','')||'Authentication failed')}finally{setBusy(false)}}
  if(!isFirebaseConfigured) return <main className="center"><section className="auth-card"><Robot/><h1>English Twin</h1><p>Firebase configuration is required once before real sign-in can run.</p><code>Add VITE_FIREBASE_* variables from .env.example</code></section></main>;
  return <main className="center"><section className="auth-card"><Robot/><div><span className="eyebrow">AI LANGUAGE COACH</span><h1>English Twin</h1><p>Learn naturally. Speak confidently. Your AI coach remembers how you learn.</p></div><div className="seg"><button className={mode==='login'?'active':''} onClick={()=>setMode('login')}>Sign in</button><button className={mode==='register'?'active':''} onClick={()=>setMode('register')}>Create account</button></div><form onSubmit={submit}>{mode==='register'&&<input placeholder="Your name" value={name} onChange={e=>setName(e.target.value)} required/>}<input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Password" minLength={6} value={password} onChange={e=>setPassword(e.target.value)} required/>{error&&<p className="error">{error}</p>}<button className="primary" type="submit" disabled={busy}>{busy?'Please wait…':mode==='login'?'Sign in':'Create account'}</button></form><button className="google" disabled={busy} onClick={async()=>{setError('');setBusy(true);try{await signInWithPopup(auth,googleProvider);nav('/')}catch(e:any){setError(e.message||'Google sign-in failed')}finally{setBusy(false)}}}>Continue with Google</button>{mode==='login'&&<button className="text" onClick={async()=>{if(!email)return setError('Enter your email first');try{await sendPasswordResetEmail(auth,email);setError('Password reset email sent.')}catch(e:any){setError(e.message||'Could not send reset email')}}}>Forgot password?</button>}</section></main> }

function Onboarding({profile,save}:{profile:Profile;save:(p:Profile)=>Promise<void>}){const [p,setP]=useState(profile);const [step,setStep]=useState(0);const [busy,setBusy]=useState(false); const steps=[<><h2>What is your main goal?</h2>{['Daily conversation','Work','Travel','Study','Moving abroad'].map(x=><Choice key={x} on={()=>setP({...p,learningGoal:x})} active={p.learningGoal===x}>{x}</Choice>)}</>,<><h2>What is your English level?</h2>{['A1','A2','B1','B2','C1'].map(x=><Choice key={x} on={()=>setP({...p,cefrLevel:x})} active={p.cefrLevel===x}>{x}</Choice>)}</>,<><h2>Daily practice target</h2>{[5,10,15,20,30].map(x=><Choice key={x} on={()=>setP({...p,dailyTargetMinutes:x})} active={p.dailyTargetMinutes===x}>{x} minutes</Choice>)}</>];return <main className="center"><section className="onboard"><Robot/><span className="eyebrow">SET UP YOUR ENGLISH TWIN</span>{steps[step]}<div className="row"><button className="secondary" disabled={!step||busy} onClick={()=>setStep(step-1)}>Back</button><button className="primary" disabled={busy} onClick={async()=>{if(step<steps.length-1)setStep(step+1);else{setBusy(true);try{await save({...p,onboardingCompleted:true})}finally{setBusy(false)}}}}>{busy?'Saving…':step<steps.length-1?'Continue':'Start learning'}</button></div></section></main>}
function Choice({children,active,on}:{children:any;active:boolean;on:()=>void}){return <button className={`choice ${active?'active':''}`} onClick={on}>{children}<span>{active?'✓':'›'}</span></button>}

function Shell({user,profile,progress,setProgress}:{user:User;profile:Profile;progress:ProgressMap;setProgress:(p:ProgressMap)=>void}){return <div className="app-shell"><div className="phone"><Routes><Route path="/" element={<Home profile={profile} progress={progress}/>}/><Route path="/learn" element={<Learn progress={progress}/>}/><Route path="/lesson/:lessonId" element={<LessonPlayer uid={user.uid} progress={progress} setProgress={setProgress}/>}/><Route path="/speak" element={<Speak/>}/><Route path="/progress" element={<Progress profile={profile} progress={progress}/>}/><Route path="/profile" element={<ProfilePage profile={profile}/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes><nav>{[['/',HomeIcon,'Home'],['/learn',BookOpen,'Learn'],['/speak',Mic,'Speak'],['/progress',ChartNoAxesCombined,'Progress'],['/profile',UserRound,'Profile']].map(([to,I,label]:any)=><NavLink end={to==='/'} key={to} to={to}><I/><small>{label}</small></NavLink>)}</nav></div></div>}
function Home({profile,progress}:{profile:Profile;progress:ProgressMap}){const nav=useNavigate();const summary=summarizeProgress(progress,lessons.length);const next=lessons.find(l=>!progress[l.id]?.completed);return <Page><header><div><span className="eyebrow">GOOD EVENING</span><h1>{profile.displayName} 👋</h1><p>Ready for a focused English session?</p></div><button className="icon"><Settings/></button></header><section className="hero"><div><span className="eyebrow">YOUR ENGLISH TWIN</span><h2>{summary.completed?'Your progress is building. Let’s keep the momentum.':'Let’s build your English foundation together.'}</h2><button className="primary" onClick={()=>nav('/speak')}><Mic/> Start talking</button></div><Robot small/></section><section><Title icon={<BrainCircuit/>}>Learning engine</Title>{summary.completed?<div className="real-stats"><div><strong>{summary.completed}</strong><span>Lessons done</span></div><div><strong>{summary.average}%</strong><span>Average score</span></div><div><strong>{summary.percent}%</strong><span>A1 path</span></div></div>:<div className="empty-engine"><Sparkles/><div><b>Personalization activates as you learn</b><p>Your Twin will turn real lesson results into smart practice.</p></div></div>}</section><section><Title icon={<Target/>}>Next mission</Title>{next?<div className="mission"><div className="mission-art">⚡</div><div><b>{next.skill}</b><h3>{next.title}</h3><small>{next.minutes} min · A1 · {next.objective}</small></div><button onClick={()=>nav(`/lesson/${next.id}`)}>Start</button></div>:<div className="insight">A1 starter path completed. Your next CEFR milestone will unlock here.</div>}</section><section><Title icon={<Sparkles/>}>AI insight</Title><div className="insight">{summary.completed?`You have completed ${summary.completed} real lessons. Future AI insights will use these results, not invented scores.`:'Complete your first lessons and your Twin will detect patterns in vocabulary, grammar and fluency.'}</div></section></Page>}
function Learn({progress}:{progress:ProgressMap}){const nav=useNavigate();return <Page><header><div><span className="eyebrow">CEFR ROADMAP</span><h1>Learn</h1><p>A structured path from foundations to fluent communication.</p></div></header><div className="levelbar"><b>A1 · Foundations</b><span>{summarizeProgress(progress,lessons.length).completed}/{lessons.length} lessons</span></div>{units.map((u,i)=><section className="unit" key={u.id}><div className="unit-head"><div className="unit-icon">{u.icon}</div><div><span>UNIT {i+1}</span><h3>{u.title}</h3></div></div><div className="lesson-list">{lessonsForUnit(u.id).map((l,j)=><button key={l.id} onClick={()=>nav(`/lesson/${l.id}`)}><span className={`lesson-index ${progress[l.id]?.completed?'done':''}`}>{progress[l.id]?.completed?'✓':j+1}</span><div><b>{l.title}</b><small>{l.minutes} min · {l.skill} · {progress[l.id]?.completed?`${progress[l.id].score}% completed`:'Not started'}</small></div><span>›</span></button>)}</div></section>)}</Page>}

function LessonPlayer({uid,progress,setProgress}:{uid:string;progress:ProgressMap;setProgress:(p:ProgressMap)=>void}){const {lessonId=''}=useParams();const lesson=lessonById(lessonId);const nav=useNavigate();const [index,setIndex]=useState(0);const [selected,setSelected]=useState('');const [fill,setFill]=useState('');const [feedback,setFeedback]=useState<{ok:boolean;text:string}|null>(null);const [correct,setCorrect]=useState(0);const [total,setTotal]=useState(0);const [finished,setFinished]=useState(false);const [saving,setSaving]=useState(false);
  if(!lesson)return <Page><button className="back" onClick={()=>nav('/learn')}><ArrowLeft/> Back</button><h2>Lesson not found</h2></Page>;
  const a=lesson.activities[index]; const progressPct=Math.round(((index+(finished?1:0))/lesson.activities.length)*100);
  async function finish(nextCorrect=correct,nextTotal=total){setSaving(true);try{const saved=await saveLessonCompletion(uid,lesson.id,nextCorrect,nextTotal);setProgress({...progress,[lesson.id]:saved});setFinished(true);}finally{setSaving(false)}}
  function advance(){setFeedback(null);setSelected('');setFill('');if(index>=lesson.activities.length-1)void finish();else setIndex(index+1)}
  function check(){if(a.type==='explain')return advance();const answer=a.type==='choice'?selected:fill.trim();if(!answer)return;const ok=answer.toLocaleLowerCase()===a.answer.toLocaleLowerCase();const nc=correct+(ok?1:0),nt=total+1;setCorrect(nc);setTotal(nt);setFeedback({ok,text:a.explanation});if(index>=lesson.activities.length-1)setTimeout(()=>void finish(nc,nt),350)}
  if(finished){const score=total?Math.round((correct/total)*100):100;return <Page><button className="back" onClick={()=>nav('/learn')}><ArrowLeft/> Learn</button><section className="lesson-complete"><CheckCircle2/><span className="eyebrow">LESSON COMPLETE</span><h1>{lesson.title}</h1><strong>{score}%</strong><p>{correct} correct out of {total} scored activities.</p><button className="primary" onClick={()=>nav('/learn')}>Continue roadmap</button></section></Page>}
  return <Page><button className="back" onClick={()=>nav('/learn')}><ArrowLeft/> Exit lesson</button><div className="lesson-top"><div><span className="eyebrow">{lesson.skill.toUpperCase()} · {lesson.minutes} MIN</span><h1>{lesson.title}</h1><p>{lesson.objective}</p></div><span>{index+1}/{lesson.activities.length}</span></div><div className="progress-track"><i style={{width:`${progressPct}%`}}/></div><section className="activity-card">{renderActivity(a,selected,setSelected,fill,setFill)}{feedback&&<div className={`feedback ${feedback.ok?'ok':'bad'}`}>{feedback.ok?<CheckCircle2/>:<XCircle/>}<div><b>{feedback.ok?'Correct':'Not quite'}</b><p>{feedback.text}</p></div></div>}<button className="primary activity-action" disabled={saving||Boolean(feedback&&index>=lesson.activities.length-1)} onClick={feedback?advance:check}>{saving?'Saving…':feedback?'Continue':a.type==='explain'?'Continue':'Check answer'}</button></section></Page>}
function renderActivity(a:Activity,selected:string,setSelected:(s:string)=>void,fill:string,setFill:(s:string)=>void){if(a.type==='explain')return <div className="explain"><span className="eyebrow">LEARN</span><h2>{a.title}</h2><p>{a.body}</p><div className="examples">{a.examples.map(x=><div key={x}>{x}</div>)}</div></div>;if(a.type==='choice')return <div><span className="eyebrow">CHOOSE THE BEST ANSWER</span><h2>{a.prompt}</h2><div className="answer-list">{a.options.map(x=><button className={selected===x?'selected':''} key={x} onClick={()=>setSelected(x)}>{x}</button>)}</div></div>;return <div><span className="eyebrow">COMPLETE THE SENTENCE</span><h2>{a.prompt}</h2><input className="lesson-input" value={fill} onChange={e=>setFill(e.target.value)} placeholder={a.hint||'Type your answer'}/></div>}

function Speak(){const [state,setState]=useState<'ready'|'listening'>('ready');return <Page><header><div><span className="eyebrow">VOICE LAB</span><h1>Speak</h1><p>Practice real English with your AI Twin.</p></div></header><section className="speak-card"><Robot/><span className={`live ${state}`}>{state==='ready'?'READY':'LISTENING…'}</span><h2>{state==='ready'?'Tell me about your day':'I’m listening'}</h2><p>Voice capture architecture is prepared; live Gemini voice will be connected through a secure service rather than a fake transcript.</p><button className="mic" onClick={()=>setState(state==='ready'?'listening':'ready')}><Mic/></button><small>{state==='ready'?'Tap to preview listening state':'Tap to stop'}</small></section><div className="quick"><button><MessageCircleMore/> Daily conversation</button><button><Volume2/> Pronunciation</button><button><Headphones/> Listening reply</button></div></Page>}
function Progress({profile,progress}:{profile:Profile;progress:ProgressMap}){const summary=summarizeProgress(progress,lessons.length);return <Page><header><div><span className="eyebrow">YOUR JOURNEY</span><h1>Progress</h1><p>Real growth, based on completed learning activity.</p></div></header><section className="level-card"><div className="badge">{profile.cefrLevel}</div><div><span>Current level</span><h2>{profile.cefrLevel} Foundations</h2><p>{summary.completed} of {summary.total} starter lessons completed.</p></div></section><section><Title icon={<ChartNoAxesCombined/>}>Learning progress</Title>{summary.completed?<><div className="progress-track large"><i style={{width:`${summary.percent}%`}}/></div><div className="real-stats"><div><strong>{summary.percent}%</strong><span>Path complete</span></div><div><strong>{summary.average}%</strong><span>Average score</span></div><div><strong>{summary.completed}</strong><span>Lessons</span></div></div></>:<div className="chart-empty"><BrainCircuit/><b>No fake scores here.</b><p>Your charts unlock from completed lessons and verified results.</p></div>}</section></Page>}
function ProfilePage({profile}:{profile:Profile}){return <Page><header><div><span className="eyebrow">ACCOUNT</span><h1>Profile</h1></div></header><section className="profile-card"><Robot small/><h2>{profile.displayName}</h2><span className="pill">{profile.cefrLevel} · {profile.learningGoal}</span></section><div className="settings-list"><button><Languages/><div><b>Interface language</b><small>{profile.interfaceLanguage}</small></div><span>›</span></button><button><Target/><div><b>Daily target</b><small>{profile.dailyTargetMinutes} minutes</small></div><span>›</span></button><button><Settings/><div><b>Preferences</b><small>Audio, notifications, privacy</small></div><span>›</span></button><button className="danger" onClick={()=>signOut(auth)}><LogOut/><div><b>Sign out</b></div></button></div></Page>}
function Title({children,icon}:{children:any;icon:any}){return <div className="section-title"><span>{icon}</span><h3>{children}</h3></div>}; function Page({children}:{children:any}){return <main className="page">{children}</main>}
export default function App(){const {user,profile,progress,setProgress,loading,save}=useSession(); if(loading)return <main className="center"><Robot/><p>Waking your English Twin…</p></main>; if(!user)return <Routes><Route path="*" element={<Auth/>}/></Routes>; if(!profile||!profile.onboardingCompleted)return <Onboarding profile={profile||defaultProfile} save={save}/>; return <Shell user={user} profile={profile} progress={progress} setProgress={setProgress}/>}
