import { SupportedLanguage } from './languageSupport';

export type FoundationCategory = 'greetings'|'family'|'food'|'home'|'numbers'|'colors'|'actions'|'places'|'body'|'needs';
export type FoundationWord = { id:string; category:FoundationCategory; emoji:string; word:string; phonetic:string; meanings:Record<SupportedLanguage,string>; example:string };

const m=(English:string,Arabic:string,Dutch:string,French:string,German:string,Spanish:string):Record<SupportedLanguage,string>=>({English,Arabic,Dutch,French,German,Spanish});

export const foundationVocabulary: FoundationWord[] = [
{ id:'hello',category:'greetings',emoji:'👋',word:'hello',phonetic:'heh-LOH',example:'Hello!',meanings:m('hello','مرحبًا','hallo','bonjour','hallo','hola') },
{ id:'bye',category:'greetings',emoji:'👋',word:'bye',phonetic:'BAI',example:'Bye!',meanings:m('bye','وداعًا','doei','au revoir','tschüss','adiós') },
{ id:'please',category:'greetings',emoji:'🙏',word:'please',phonetic:'PLEEZ',example:'Please.',meanings:m('please','من فضلك','alsjeblieft','s’il vous plaît','bitte','por favor') },
{ id:'thanks',category:'greetings',emoji:'🤝',word:'thanks',phonetic:'THANKS',example:'Thanks!',meanings:m('thanks','شكرًا','bedankt','merci','danke','gracias') },
{ id:'yes',category:'greetings',emoji:'✅',word:'yes',phonetic:'YES',example:'Yes, please.',meanings:m('yes','نعم','ja','oui','ja','sí') },
{ id:'no',category:'greetings',emoji:'❌',word:'no',phonetic:'NOH',example:'No, thanks.',meanings:m('no','لا','nee','non','nein','no') },
{ id:'mother',category:'family',emoji:'👩',word:'mother',phonetic:'MUH-ther',example:'My mother.',meanings:m('mother','أم','moeder','mère','Mutter','madre') },
{ id:'father',category:'family',emoji:'👨',word:'father',phonetic:'FAH-ther',example:'My father.',meanings:m('father','أب','vader','père','Vater','padre') },
{ id:'sister',category:'family',emoji:'👧',word:'sister',phonetic:'SIS-ter',example:'My sister.',meanings:m('sister','أخت','zus','sœur','Schwester','hermana') },
{ id:'brother',category:'family',emoji:'👦',word:'brother',phonetic:'BRUH-ther',example:'My brother.',meanings:m('brother','أخ','broer','frère','Bruder','hermano') },
{ id:'baby',category:'family',emoji:'👶',word:'baby',phonetic:'BAY-bee',example:'The baby.',meanings:m('baby','رضيع','baby','bébé','Baby','bebé') },
{ id:'family',category:'family',emoji:'👨‍👩‍👧‍👦',word:'family',phonetic:'FAM-uh-lee',example:'My family.',meanings:m('family','عائلة','familie','famille','Familie','familia') },
{ id:'water',category:'food',emoji:'💧',word:'water',phonetic:'WAW-ter',example:'Water, please.',meanings:m('water','ماء','water','eau','Wasser','agua') },
{ id:'apple',category:'food',emoji:'🍎',word:'apple',phonetic:'AP-uhl',example:'An apple.',meanings:m('apple','تفاحة','appel','pomme','Apfel','manzana') },
{ id:'bread',category:'food',emoji:'🍞',word:'bread',phonetic:'BRED',example:'Bread, please.',meanings:m('bread','خبز','brood','pain','Brot','pan') },
{ id:'coffee',category:'food',emoji:'☕',word:'coffee',phonetic:'KAW-fee',example:'Coffee, please.',meanings:m('coffee','قهوة','koffie','café','Kaffee','café') },
{ id:'milk',category:'food',emoji:'🥛',word:'milk',phonetic:'MILK',example:'I drink milk.',meanings:m('milk','حليب','melk','lait','Milch','leche') },
{ id:'rice',category:'food',emoji:'🍚',word:'rice',phonetic:'RAIS',example:'I eat rice.',meanings:m('rice','أرز','rijst','riz','Reis','arroz') },
{ id:'home',category:'home',emoji:'🏠',word:'home',phonetic:'HOHM',example:'I am home.',meanings:m('home','المنزل','thuis','maison','Zuhause','casa') },
{ id:'door',category:'home',emoji:'🚪',word:'door',phonetic:'DOR',example:'Open the door.',meanings:m('door','باب','deur','porte','Tür','puerta') },
{ id:'bed',category:'home',emoji:'🛏️',word:'bed',phonetic:'BED',example:'My bed.',meanings:m('bed','سرير','bed','lit','Bett','cama') },
{ id:'table',category:'home',emoji:'🪑',word:'table',phonetic:'TAY-buhl',example:'On the table.',meanings:m('table','طاولة','tafel','table','Tisch','mesa') },
{ id:'chair',category:'home',emoji:'🪑',word:'chair',phonetic:'CHAIR',example:'A chair.',meanings:m('chair','كرسي','stoel','chaise','Stuhl','silla') },
{ id:'room',category:'home',emoji:'🛋️',word:'room',phonetic:'ROOM',example:'My room.',meanings:m('room','غرفة','kamer','chambre','Zimmer','habitación') },
{ id:'one',category:'numbers',emoji:'1️⃣',word:'one',phonetic:'WUN',example:'One coffee.',meanings:m('one','واحد','één','un','eins','uno') },
{ id:'two',category:'numbers',emoji:'2️⃣',word:'two',phonetic:'TOO',example:'Two apples.',meanings:m('two','اثنان','twee','deux','zwei','dos') },
{ id:'three',category:'numbers',emoji:'3️⃣',word:'three',phonetic:'THREE',example:'Three people.',meanings:m('three','ثلاثة','drie','trois','drei','tres') },
{ id:'four',category:'numbers',emoji:'4️⃣',word:'four',phonetic:'FOR',example:'Four chairs.',meanings:m('four','أربعة','vier','quatre','vier','cuatro') },
{ id:'five',category:'numbers',emoji:'5️⃣',word:'five',phonetic:'FAIV',example:'Five minutes.',meanings:m('five','خمسة','vijf','cinq','fünf','cinco') },
{ id:'ten',category:'numbers',emoji:'🔟',word:'ten',phonetic:'TEN',example:'Ten euros.',meanings:m('ten','عشرة','tien','dix','zehn','diez') },
{ id:'red',category:'colors',emoji:'🔴',word:'red',phonetic:'RED',example:'A red apple.',meanings:m('red','أحمر','rood','rouge','rot','rojo') },
{ id:'blue',category:'colors',emoji:'🔵',word:'blue',phonetic:'BLOO',example:'A blue bag.',meanings:m('blue','أزرق','blauw','bleu','blau','azul') },
{ id:'green',category:'colors',emoji:'🟢',word:'green',phonetic:'GREEN',example:'A green door.',meanings:m('green','أخضر','groen','vert','grün','verde') },
{ id:'black',category:'colors',emoji:'⚫',word:'black',phonetic:'BLAK',example:'A black car.',meanings:m('black','أسود','zwart','noir','schwarz','negro') },
{ id:'white',category:'colors',emoji:'⚪',word:'white',phonetic:'WAIT',example:'A white cup.',meanings:m('white','أبيض','wit','blanc','weiß','blanco') },
{ id:'yellow',category:'colors',emoji:'🟡',word:'yellow',phonetic:'YEL-oh',example:'A yellow bus.',meanings:m('yellow','أصفر','geel','jaune','gelb','amarillo') },
{ id:'go',category:'actions',emoji:'🚶',word:'go',phonetic:'GOH',example:'I go home.',meanings:m('go','يذهب','gaan','aller','gehen','ir') },
{ id:'come',category:'actions',emoji:'➡️',word:'come',phonetic:'KUM',example:'Come here.',meanings:m('come','يأتي','komen','venir','kommen','venir') },
{ id:'eat',category:'actions',emoji:'🍽️',word:'eat',phonetic:'EET',example:'I eat bread.',meanings:m('eat','يأكل','eten','manger','essen','comer') },
{ id:'drink',category:'actions',emoji:'🥤',word:'drink',phonetic:'DRINK',example:'I drink water.',meanings:m('drink','يشرب','drinken','boire','trinken','beber') },
{ id:'sleep',category:'actions',emoji:'😴',word:'sleep',phonetic:'SLEEP',example:'I sleep.',meanings:m('sleep','ينام','slapen','dormir','schlafen','dormir') },
{ id:'work',category:'actions',emoji:'💼',word:'work',phonetic:'WURK',example:'I work today.',meanings:m('work','يعمل','werken','travailler','arbeiten','trabajar') },
{ id:'school',category:'places',emoji:'🏫',word:'school',phonetic:'SKOOL',example:'At school.',meanings:m('school','مدرسة','school','école','Schule','escuela') },
{ id:'station',category:'places',emoji:'🚉',word:'station',phonetic:'STAY-shuhn',example:'The station.',meanings:m('station','محطة','station','gare','Bahnhof','estación') },
{ id:'shop',category:'places',emoji:'🛒',word:'shop',phonetic:'SHOP',example:'At the shop.',meanings:m('shop','متجر','winkel','magasin','Geschäft','tienda') },
{ id:'hospital',category:'places',emoji:'🏥',word:'hospital',phonetic:'HOS-pi-tuhl',example:'The hospital.',meanings:m('hospital','مستشفى','ziekenhuis','hôpital','Krankenhaus','hospital') },
{ id:'toilet',category:'places',emoji:'🚻',word:'toilet',phonetic:'TOY-luht',example:'Where is the toilet?',meanings:m('toilet','مرحاض','toilet','toilettes','Toilette','baño') },
{ id:'street',category:'places',emoji:'🛣️',word:'street',phonetic:'STREET',example:'This street.',meanings:m('street','شارع','straat','rue','Straße','calle') },
{ id:'head',category:'body',emoji:'🙂',word:'head',phonetic:'HED',example:'My head.',meanings:m('head','رأس','hoofd','tête','Kopf','cabeza') },
{ id:'hand',category:'body',emoji:'✋',word:'hand',phonetic:'HAND',example:'My hand.',meanings:m('hand','يد','hand','main','Hand','mano') },
{ id:'eye',category:'body',emoji:'👁️',word:'eye',phonetic:'AI',example:'My eye.',meanings:m('eye','عين','oog','œil','Auge','ojo') },
{ id:'mouth',category:'body',emoji:'👄',word:'mouth',phonetic:'MOUTH',example:'My mouth.',meanings:m('mouth','فم','mond','bouche','Mund','boca') },
{ id:'foot',category:'body',emoji:'🦶',word:'foot',phonetic:'FOOT',example:'My foot.',meanings:m('foot','قدم','voet','pied','Fuß','pie') },
{ id:'body',category:'body',emoji:'🧍',word:'body',phonetic:'BAH-dee',example:'My body.',meanings:m('body','جسم','lichaam','corps','Körper','cuerpo') },
{ id:'help',category:'needs',emoji:'🆘',word:'help',phonetic:'HELP',example:'Help, please.',meanings:m('help','مساعدة','hulp','aide','Hilfe','ayuda') },
{ id:'hungry',category:'needs',emoji:'🍽️',word:'hungry',phonetic:'HUNG-gree',example:'I am hungry.',meanings:m('hungry','جائع','hongerig','faim','hungrig','hambriento') },
{ id:'thirsty',category:'needs',emoji:'🥤',word:'thirsty',phonetic:'THUR-stee',example:'I am thirsty.',meanings:m('thirsty','عطشان','dorstig','soif','durstig','sediento') },
{ id:'tired',category:'needs',emoji:'🥱',word:'tired',phonetic:'TAI-erd',example:'I am tired.',meanings:m('tired','متعب','moe','fatigué','müde','cansado') },
{ id:'pain',category:'needs',emoji:'🤕',word:'pain',phonetic:'PAYN',example:'I have pain.',meanings:m('pain','ألم','pijn','douleur','Schmerz','dolor') },
{ id:'name',category:'needs',emoji:'🪪',word:'name',phonetic:'NAYM',example:'My name is Amir.',meanings:m('name','اسم','naam','nom','Name','nombre') },
];

export const foundationCategories: FoundationCategory[]=['greetings','family','food','home','numbers','colors','actions','places','body','needs'];
