import { useEffect, useState } from 'react';
import { Navigate, useNavigate, useParams } from 'react-router-dom';
import { onAuthStateChanged, User } from 'firebase/auth';
import { doc, getDoc } from 'firebase/firestore';
import { ArrowLeft, CheckCircle2, ChevronRight, Languages, XCircle } from 'lucide-react';
import AppDock from './AppDock';
import { auth, db } from './firebase';
import { Activity, Lesson, lessonById, lessonsForLevel, lessonsForUnit, units } from './curriculumAll';
import { loadLessonProgress, ProgressMap, saveLessonCompletion, summarizeProgress } from './learning';
import { directionFor, immersionSupportPercent, normalizeLanguage, SupportedLanguage, t } from './languageSupport';

type LearnerProfile = { nativeLanguage?: string; explanationLanguage?: string; interfaceLanguage?: string; cefrLevel?: string; learningGoal?: string };

type PathCopy = { loadingPath:string; roadmap:string; learn:string; intro:(language:string)=>string; supportNote:(percent:number)=>string; foundations:string; independence:string; completed:(done:number,total:number)=>string; unit:string; start:string; loadingLesson:string; backLearn:string; notFound:string; lessonComplete:string; score:(correct:number,total:number)=>string; continueRoadmap:string; exit:string; supportChip:(language:string)=>string; saving:string };
const pathCopy: Record<SupportedLanguage, PathCopy> = {
 English:{loadingPath:'Loading your learning path…',roadmap:'CEFR ROADMAP',learn:'Learn',intro:l=>`Structured English, supported in ${l} when you need it.`,supportNote:p=>`${p}% native-language support at your current level · answers stay in English`,foundations:'Foundations',independence:'Real-world independence',completed:(d,t)=>`${d} of ${t} lessons completed`,unit:'UNIT',start:'Start',loadingLesson:'Loading lesson…',backLearn:'Learn',notFound:'Lesson not found',lessonComplete:'LESSON COMPLETE',score:(c,t)=>`${c} correct out of ${t} scored activities.`,continueRoadmap:'Continue roadmap',exit:'Exit lesson',supportChip:l=>`${l} support · English target`,saving:'Saving…'},
 Arabic:{loadingPath:'نحمّل مسار تعلّمك…',roadmap:'مسار CEFR',learn:'تعلّم',intro:l=>`إنجليزية منظمة مع دعم باللغة ${l} عند الحاجة.`,supportNote:p=>`${p}% دعم بلغتك في مستواك الحالي · الإجابات تبقى بالإنجليزية`,foundations:'الأساسيات',independence:'الاستقلال في مواقف الحياة',completed:(d,t)=>`أكملت ${d} من ${t} درسًا`,unit:'الوحدة',start:'ابدأ',loadingLesson:'نحمّل الدرس…',backLearn:'التعلّم',notFound:'الدرس غير موجود',lessonComplete:'اكتمل الدرس',score:(c,t)=>`${c} إجابة صحيحة من ${t} نشاطًا محسوبًا.`,continueRoadmap:'تابع المسار',exit:'اخرج من الدرس',supportChip:l=>`دعم ${l} · الهدف إنجليزي`,saving:'جارٍ الحفظ…'},
 Dutch:{loadingPath:'Je leerpad wordt geladen…',roadmap:'CEFR-LEERPAD',learn:'Leren',intro:l=>`Gestructureerd Engels met ondersteuning in ${l} wanneer je die nodig hebt.`,supportNote:p=>`${p}% ondersteuning in je moedertaal op je huidige niveau · antwoorden blijven Engels`,foundations:'Basis',independence:'Zelfstandig in de praktijk',completed:(d,t)=>`${d} van ${t} lessen voltooid`,unit:'UNIT',start:'Start',loadingLesson:'Les wordt geladen…',backLearn:'Leren',notFound:'Les niet gevonden',lessonComplete:'LES VOLTOOID',score:(c,t)=>`${c} goed van ${t} beoordeelde activiteiten.`,continueRoadmap:'Ga verder met het leerpad',exit:'Les verlaten',supportChip:l=>`${l} ondersteuning · Engels als doeltaal`,saving:'Opslaan…'},
 French:{loadingPath:'Chargement de ton parcours…',roadmap:'PARCOURS CECR',learn:'Apprendre',intro:l=>`Un anglais structuré avec un soutien en ${l} quand tu en as besoin.`,supportNote:p=>`${p}% de soutien dans ta langue à ton niveau actuel · les réponses restent en anglais`,foundations:'Fondations',independence:'Autonomie réelle',completed:(d,t)=>`${d} leçons terminées sur ${t}`,unit:'UNITÉ',start:'Commencer',loadingLesson:'Chargement de la leçon…',backLearn:'Apprendre',notFound:'Leçon introuvable',lessonComplete:'LEÇON TERMINÉE',score:(c,t)=>`${c} bonnes réponses sur ${t} activités notées.`,continueRoadmap:'Continuer le parcours',exit:'Quitter la leçon',supportChip:l=>`Soutien en ${l} · anglais cible`,saving:'Enregistrement…'},
 German:{loadingPath:'Dein Lernpfad wird geladen…',roadmap:'CEFR-LERNPFAD',learn:'Lernen',intro:l=>`Strukturiertes Englisch mit Unterstützung auf ${l}, wenn du sie brauchst.`,supportNote:p=>`${p}% Unterstützung in deiner Sprache auf deinem aktuellen Niveau · Antworten bleiben Englisch`,foundations:'Grundlagen',independence:'Selbstständig im Alltag',completed:(d,t)=>`${d} von ${t} Lektionen abgeschlossen`,unit:'EINHEIT',start:'Start',loadingLesson:'Lektion wird geladen…',backLearn:'Lernen',notFound:'Lektion nicht gefunden',lessonComplete:'LEKTION ABGESCHLOSSEN',score:(c,t)=>`${c} von ${t} bewerteten Aufgaben richtig.`,continueRoadmap:'Lernpfad fortsetzen',exit:'Lektion verlassen',supportChip:l=>`${l}-Unterstützung · Zielsprache Englisch`,saving:'Speichern…'},
 Spanish:{loadingPath:'Cargando tu ruta de aprendizaje…',roadmap:'RUTA MCER',learn:'Aprender',intro:l=>`Inglés estructurado con apoyo en ${l} cuando lo necesites.`,supportNote:p=>`${p}% de apoyo en tu idioma en tu nivel actual · las respuestas siguen en inglés`,foundations:'Fundamentos',independence:'Autonomía en la vida real',completed:(d,t)=>`${d} de ${t} lecciones completadas`,unit:'UNIDAD',start:'Empezar',loadingLesson:'Cargando lección…',backLearn:'Aprender',notFound:'Lección no encontrada',lessonComplete:'LECCIÓN COMPLETADA',score:(c,t)=>`${c} correctas de ${t} actividades evaluadas.`,continueRoadmap:'Continuar la ruta',exit:'Salir de la lección',supportChip:l=>`Apoyo en ${l} · objetivo inglés`,saving:'Guardando…'},
};

function Frame({ children, language }: { children: React.ReactNode; language?: string }) { return <div className="app-shell" dir={directionFor(language)}><div className="phone"><main className="page">{children}</main><AppDock language={language} /></div></div> }
function usePathLearner(){const[user,setUser]=useState<User|null>(null);const[profile,setProfile]=useState<LearnerProfile>({});const[progress,setProgress]=useState<ProgressMap>({});const[loading,setLoading]=useState(true);useEffect(()=>onAuthStateChanged(auth,async current=>{setUser(current);if(!current){setProfile({});setProgress({});setLoading(false);return}try{const[learnerProgress,profileSnap]=await Promise.all([loadLessonProgress(current.uid),getDoc(doc(db,'users',current.uid))]);setProgress(learnerProgress);setProfile(profileSnap.exists()?profileSnap.data() as LearnerProfile:{})}finally{setLoading(false)}}),[]);return{user,profile,progress,setProgress,loading}}
function supportLanguageFor(profile:LearnerProfile){return normalizeLanguage(profile.explanationLanguage||profile.nativeLanguage||profile.interfaceLanguage||'English')}

export function LearnJourney(){const{user,profile,progress,loading}=usePathLearner();const nav=useNavigate();const supportLanguage=supportLanguageFor(profile);const copy=pathCopy[supportLanguage];if(loading)return <Frame language={supportLanguage}><p>{copy.loadingPath}</p></Frame>;if(!user)return <Navigate to="/welcome" replace/>;const levels:Array<'A1'|'A2'>=['A1','A2'];return <Frame language={supportLanguage}>
<header><div><span className="eyebrow">{copy.roadmap}</span><h1>{copy.learn}</h1><p>{copy.intro(supportLanguage)}</p></div></header>
<div className="language-support-banner"><Languages/><div><b>{t(supportLanguage,'support')}: {supportLanguage}</b><small>{copy.supportNote(immersionSupportPercent(profile.cefrLevel))}</small></div></div>
{levels.map(level=>{const levelLessons=lessonsForLevel(level),summary=summarizeProgress(progress,levelLessons.length),levelUnits=units.filter(unit=>level==='A2'?unit.id.startsWith('a2-'):!unit.id.startsWith('a2-'));return <section key={level} className="level-section"><div className="learn-overview"><div><span>{level} · {level==='A1'?copy.foundations:copy.independence}</span><strong>{summary.percent}%</strong></div><div className="thin-progress"><i style={{width:`${summary.percent}%`}}/></div><small>{copy.completed(summary.completed,summary.total)}</small></div><div className="journey">{levelUnits.map((unit,unitIndex)=><section className="journey-unit" key={unit.id}><div className="journey-marker"><span>{unitIndex+1}</span></div><div className="journey-content"><div className="unit-label"><small>{level} · {copy.unit} {String(unitIndex+1).padStart(2,'0')}</small><h3>{unit.title.replace(/^A2 · /,'')}</h3></div><div className="lesson-rows">{lessonsForUnit(unit.id).map(lesson=>{const result=progress[lesson.id];return <button key={lesson.id} onClick={()=>nav(`/lesson/${lesson.id}`)}><div><b>{lesson.title}</b><small>{lesson.skill} · {lesson.minutes} min</small></div><span className={result?.completed?'done':''}>{result?.completed?`${result.score}%`:copy.start} <ChevronRight/></span></button>})}</div></div></section>)}</div></section>})}</Frame>}

function renderActivity(activity:Activity,selected:string,setSelected:(value:string)=>void,fill:string,setFill:(value:string)=>void,supportLanguage:string){const dir=directionFor(supportLanguage);if(activity.type==='explain')return <div className="explain"><span className="eyebrow" dir={dir}>{t(supportLanguage,'learn')}</span><div className="native-instruction" dir={dir}>{t(supportLanguage,'nativeQuestion')}</div><h2>{activity.title}</h2><p>{activity.body}</p><div className="examples">{activity.examples.map(example=><div key={example}>{example}</div>)}</div></div>;if(activity.type==='choice')return <div><span className="eyebrow" dir={dir}>{t(supportLanguage,'choose')}</span><div className="native-instruction" dir={dir}>{t(supportLanguage,'target')}</div><h2>{activity.prompt}</h2><div className="answer-list">{activity.options.map(option=><button className={selected===option?'selected':''} key={option} onClick={()=>setSelected(option)}>{option}</button>)}</div></div>;return <div><span className="eyebrow" dir={dir}>{t(supportLanguage,'fill')}</span><div className="native-instruction" dir={dir}>{t(supportLanguage,'target')}</div><h2>{activity.prompt}</h2><input className="lesson-input" value={fill} onChange={event=>setFill(event.target.value)} placeholder={activity.hint||t(supportLanguage,'hint')}/></div>}

export function UnifiedLessonPlayer(){const{lessonId=''}=useParams();const nav=useNavigate();const{user,profile,progress,setProgress,loading}=usePathLearner();const[index,setIndex]=useState(0);const[selected,setSelected]=useState('');const[fill,setFill]=useState('');const[feedback,setFeedback]=useState<{ok:boolean;text:string}|null>(null);const[correct,setCorrect]=useState(0);const[total,setTotal]=useState(0);const[finished,setFinished]=useState(false);const[saving,setSaving]=useState(false);let lesson:Lesson|null=null;try{lesson=lessonById(lessonId)}catch{lesson=null}const supportLanguage=supportLanguageFor(profile),copy=pathCopy[supportLanguage];if(loading)return <Frame language={supportLanguage}><p>{copy.loadingLesson}</p></Frame>;if(!user)return <Navigate to="/welcome" replace/>;if(!lesson)return <Frame language={supportLanguage}><button className="back" onClick={()=>nav('/learn')}><ArrowLeft/> {copy.backLearn}</button><h2>{copy.notFound}</h2></Frame>;
const uid=user.uid,currentLesson=lesson,activity=currentLesson.activities[index],progressPercent=Math.round(((index+(finished?1:0))/currentLesson.activities.length)*100);
async function finish(nextCorrect=correct,nextTotal=total){setSaving(true);try{const saved=await saveLessonCompletion(uid,currentLesson.id,nextCorrect,nextTotal);setProgress({...progress,[currentLesson.id]:saved});setFinished(true)}finally{setSaving(false)}}
function advance(){setFeedback(null);setSelected('');setFill('');if(index>=currentLesson.activities.length-1)void finish();else setIndex(index+1)}
function check(){if(activity.type==='explain')return advance();const answer=activity.type==='choice'?selected:fill.trim();if(!answer)return;const ok=answer.toLocaleLowerCase()===activity.answer.toLocaleLowerCase();const nextCorrect=correct+(ok?1:0),nextTotal=total+1;setCorrect(nextCorrect);setTotal(nextTotal);setFeedback({ok,text:activity.explanation});if(index>=currentLesson.activities.length-1)setTimeout(()=>void finish(nextCorrect,nextTotal),250)}
if(finished){const score=total?Math.round((correct/total)*100):100;return <Frame language={supportLanguage}><button className="back" onClick={()=>nav('/learn')}><ArrowLeft/> {copy.backLearn}</button><section className="lesson-complete"><CheckCircle2/><span className="eyebrow">{copy.lessonComplete}</span><h1>{currentLesson.title}</h1><strong>{score}%</strong><p>{copy.score(correct,total)}</p><button className="primary" onClick={()=>nav('/learn')}>{copy.continueRoadmap}</button></section></Frame>}
return <Frame language={supportLanguage}><button className="back" onClick={()=>nav('/learn')}><ArrowLeft/> {copy.exit}</button><div className="lesson-top"><div><span className="eyebrow">{currentLesson.id.startsWith('a2-')?'A2':'A1'} · {currentLesson.skill.toUpperCase()} · {currentLesson.minutes} MIN</span><h1>{currentLesson.title}</h1><p>{currentLesson.objective}</p></div><span>{index+1}/{currentLesson.activities.length}</span></div><div className="lesson-language-chip"><Languages/> {copy.supportChip(supportLanguage)}</div><div className="progress-track"><i style={{width:`${progressPercent}%`}}/></div><section className="activity-card">{renderActivity(activity,selected,setSelected,fill,setFill,supportLanguage)}{feedback&&<div className={`feedback ${feedback.ok?'ok':'bad'}`}>{feedback.ok?<CheckCircle2/>:<XCircle/>}<div><b>{feedback.ok?t(supportLanguage,'correct'):t(supportLanguage,'retry')}</b><small className="feedback-label">{t(supportLanguage,'explanation')}</small><p>{feedback.text}</p></div></div>}<button className="primary activity-action" disabled={saving||Boolean(feedback&&index>=currentLesson.activities.length-1)} onClick={feedback?advance:check}>{saving?copy.saving:feedback?t(supportLanguage,'continue'):activity.type==='explain'?t(supportLanguage,'continue'):t(supportLanguage,'check')}</button></section></Frame>}
