import type { SupportedLanguage } from './languageSupport';

type PrivacyCopy = {
  back: string;
  eyebrow: string;
  title: string;
  intro: string;
  scopedTitle: string;
  scopedBody: string;
  aiTitle: string;
  aiBody: string;
  voiceTitle: string;
  voiceBody: string;
  control: string;
  choices: string;
  micTitle: string;
  micBody: string;
  aiChoiceTitle: string;
  aiChoiceBody: string;
  deleteTitle: string;
  deleteBody: string;
  retentionTitle: string;
  retentionBody: string;
  releaseTitle: string;
  releaseBody: string;
};

export const privacySupportCopy: Record<SupportedLanguage, PrivacyCopy> = {
  English: {
    back:'Back', eyebrow:'ENGLISH TWIN · PRIVACY', title:'Privacy & AI data', intro:'This page explains, in plain language, what English Twin stores, why it is used, when AI services receive data and how you can delete it.', scopedTitle:'Your learning data stays account-scoped.', scopedBody:'Progress, review cards, review history, mistakes, profile settings, Twin memory and saved learning sessions are stored under your signed-in account. Access rules restrict user-owned data to that account.', aiTitle:'AI Twin uses bounded learning context.', aiBody:'When you use AI Twin, the app may send your message plus a limited snapshot of relevant learning context such as recent mistakes, due review terms, completed lessons and recent conversation context to the configured AI service. Passwords are never included in AI prompts.', voiceTitle:'Voice features require explicit microphone permission.', voiceBody:'Live speaking can stream microphone audio to the configured live AI service only after you approve the voice consent screen. The resulting transcript and basic session metadata may be stored in your account to support progress and later practice.', control:'CONTROL', choices:'Your choices', micTitle:'Microphone access', micBody:'You can refuse microphone permission and continue using non-voice learning modes.', aiChoiceTitle:'AI features', aiChoiceBody:'Core lessons, review and deterministic practice can operate separately from free-form AI chat and Live speaking.', deleteTitle:'Delete your account and learning data', deleteBody:'From Profile → Delete account, you can permanently remove your profile, lesson progress, review history, saved mistakes, Twin memory, saved Live transcripts and sign-in account. A recent sign-in is required before destructive deletion begins.', retentionTitle:'Retention', retentionBody:'User-owned learning records are retained while the account remains active so English Twin can preserve progress and adaptive memory. Account deletion removes the app-managed user records covered above. Infrastructure and AI services may separately retain limited operational or security records under their own policies.', releaseTitle:'Release note', releaseBody:'This in-app disclosure describes the product’s current data behavior. Before a public commercial launch, the published store/site privacy policy should also include the operator’s legal identity, support/privacy contact details and any jurisdiction-specific disclosures required for the launch markets.'
  },
  Arabic: {
    back:'رجوع', eyebrow:'ENGLISH TWIN · الخصوصية', title:'الخصوصية وبيانات الذكاء الاصطناعي', intro:'تشرح هذه الصفحة بلغة واضحة ما الذي يحفظه English Twin، ولماذا يُستخدم، ومتى تُرسل بيانات إلى خدمات الذكاء الاصطناعي وكيف يمكنك حذفها.', scopedTitle:'بيانات تعلّمك مرتبطة بحسابك فقط.', scopedBody:'يتم حفظ التقدم، وبطاقات المراجعة، وسجل المراجعة، والأخطاء، وإعدادات الملف، وذاكرة Twin، وجلسات التعلم المحفوظة ضمن حسابك المسجل. قواعد الوصول تقصر بيانات المستخدم على ذلك الحساب.', aiTitle:'يستخدم AI Twin سياقًا تعليميًا محدودًا.', aiBody:'عند استخدام AI Twin قد يرسل التطبيق رسالتك مع جزء محدود من سياق التعلم ذي الصلة، مثل الأخطاء الأخيرة والمراجعات المستحقة والدروس المكتملة وسياق المحادثة الحديث، إلى خدمة الذكاء الاصطناعي المهيأة. كلمات المرور لا تُضمّن في مطالبات الذكاء الاصطناعي.', voiceTitle:'ميزات الصوت تحتاج إذنًا صريحًا للميكروفون.', voiceBody:'يمكن للمحادثة الحية إرسال صوت الميكروفون إلى خدمة الصوت الحية المهيأة فقط بعد موافقتك على شاشة الإذن. قد يُحفظ النص الناتج وبيانات الجلسة الأساسية في حسابك لدعم التقدم والتدريب لاحقًا.', control:'التحكم', choices:'خياراتك', micTitle:'الوصول إلى الميكروفون', micBody:'يمكنك رفض إذن الميكروفون ومواصلة استخدام أوضاع التعلم غير الصوتية.', aiChoiceTitle:'ميزات الذكاء الاصطناعي', aiChoiceBody:'يمكن للدروس الأساسية والمراجعة والتدريب المحدد العمل بشكل منفصل عن المحادثة الحرة مع الذكاء الاصطناعي والكلام الحي.', deleteTitle:'حذف حسابك وبيانات التعلم', deleteBody:'من الملف الشخصي ← حذف الحساب، يمكنك حذف ملفك وتقدم الدروس وسجل المراجعة والأخطاء المحفوظة وذاكرة Twin ونصوص المحادثات الحية وحساب تسجيل الدخول نهائيًا. يلزم تسجيل دخول حديث قبل بدء الحذف.', retentionTitle:'الاحتفاظ بالبيانات', retentionBody:'تُحتفظ سجلات التعلم التي يملكها المستخدم ما دام الحساب نشطًا حتى يحافظ English Twin على التقدم والذاكرة التكيفية. حذف الحساب يزيل سجلات التطبيق المذكورة أعلاه. قد تحتفظ البنية التحتية وخدمات الذكاء الاصطناعي بسجلات تشغيل أو أمان محدودة وفق سياساتها.', releaseTitle:'ملاحظة النشر', releaseBody:'يصف هذا الإفصاح داخل التطبيق سلوك البيانات الحالي للمنتج. قبل الإطلاق التجاري العام يجب أن تتضمن سياسة الخصوصية المنشورة أيضًا الهوية القانونية للمشغّل وبيانات التواصل والدعم وأي إفصاحات مطلوبة في أسواق الإطلاق.'
  },
  Dutch: {
    back:'Terug', eyebrow:'ENGLISH TWIN · PRIVACY', title:'Privacy & AI-gegevens', intro:'Deze pagina legt in gewone taal uit welke gegevens English Twin bewaart, waarom, wanneer AI-diensten gegevens ontvangen en hoe je ze kunt verwijderen.', scopedTitle:'Je leergegevens blijven aan jouw account gekoppeld.', scopedBody:'Voortgang, herhaalkaarten, herhaalgeschiedenis, fouten, profielinstellingen, Twin-geheugen en opgeslagen leersessies worden onder je ingelogde account bewaard. Toegangsregels beperken gebruikersgegevens tot dat account.', aiTitle:'AI Twin gebruikt beperkte leercontext.', aiBody:'Wanneer je AI Twin gebruikt, kan de app je bericht plus een beperkte selectie relevante leercontext sturen, zoals recente fouten, openstaande herhalingen, afgeronde lessen en recente gesprekscontext, naar de ingestelde AI-dienst. Wachtwoorden worden nooit in AI-prompts opgenomen.', voiceTitle:'Spraakfuncties vragen expliciete microfoontoestemming.', voiceBody:'Live spreken kan microfoonaudio pas naar de ingestelde live-AI-dienst sturen nadat je toestemming hebt gegeven. Het resulterende transcript en basisgegevens van de sessie kunnen in je account worden opgeslagen voor voortgang en latere oefening.', control:'BEHEER', choices:'Jouw keuzes', micTitle:'Microfoontoegang', micBody:'Je kunt microfoontoegang weigeren en de niet-spraakgerichte leermodi blijven gebruiken.', aiChoiceTitle:'AI-functies', aiChoiceBody:'Kernlessen, herhaling en deterministische oefeningen kunnen los van vrije AI-chat en Live spreken werken.', deleteTitle:'Je account en leergegevens verwijderen', deleteBody:'Via Profiel → Account verwijderen kun je je profiel, lesvoortgang, herhaalgeschiedenis, opgeslagen fouten, Twin-geheugen, opgeslagen Live-transcripten en inlogaccount permanent verwijderen. Een recente aanmelding is vereist voordat de verwijdering begint.', retentionTitle:'Bewaartermijn', retentionBody:'Leergegevens van de gebruiker blijven bewaard zolang het account actief is, zodat English Twin voortgang en adaptief geheugen kan behouden. Accountverwijdering wist de hierboven genoemde app-gegevens. Infrastructuur- en AI-diensten kunnen beperkte operationele of beveiligingsgegevens volgens hun eigen beleid bewaren.', releaseTitle:'Publicatienotitie', releaseBody:'Deze uitleg beschrijft het huidige datagedrag van het product. Voor een openbare commerciële lancering moet het gepubliceerde privacybeleid ook de juridische identiteit van de aanbieder, contactgegevens en eventuele marktgebonden verplichte informatie bevatten.'
  },
  French: {
    back:'Retour', eyebrow:'ENGLISH TWIN · CONFIDENTIALITÉ', title:'Confidentialité et données IA', intro:'Cette page explique simplement ce que English Twin stocke, pourquoi, quand des services d’IA reçoivent des données et comment les supprimer.', scopedTitle:'Tes données d’apprentissage restent liées à ton compte.', scopedBody:'Progression, cartes de révision, historique, erreurs, réglages du profil, mémoire Twin et sessions enregistrées sont stockés sous ton compte connecté. Les règles d’accès limitent les données utilisateur à ce compte.', aiTitle:'AI Twin utilise un contexte d’apprentissage limité.', aiBody:'Lorsque tu utilises AI Twin, l’application peut envoyer ton message avec un extrait limité du contexte d’apprentissage pertinent, comme les erreurs récentes, les révisions dues, les leçons terminées et le contexte récent de conversation, au service d’IA configuré. Les mots de passe ne sont jamais inclus dans les prompts.', voiceTitle:'Les fonctions vocales nécessitent une autorisation explicite du microphone.', voiceBody:'La conversation en direct peut transmettre l’audio du microphone au service d’IA vocal configuré uniquement après ton accord. Le transcript obtenu et des métadonnées de base de session peuvent être stockés dans ton compte pour suivre la progression et préparer de futurs exercices.', control:'CONTRÔLE', choices:'Tes choix', micTitle:'Accès au microphone', micBody:'Tu peux refuser l’accès au microphone et continuer à utiliser les modes d’apprentissage non vocaux.', aiChoiceTitle:'Fonctions IA', aiChoiceBody:'Les leçons principales, la révision et les exercices déterministes peuvent fonctionner séparément du chat IA libre et de la conversation Live.', deleteTitle:'Supprimer ton compte et tes données', deleteBody:'Depuis Profil → Supprimer le compte, tu peux supprimer définitivement ton profil, ta progression, l’historique des révisions, les erreurs enregistrées, la mémoire Twin, les transcriptions Live et ton compte de connexion. Une connexion récente est requise avant la suppression.', retentionTitle:'Conservation', retentionBody:'Les données d’apprentissage de l’utilisateur sont conservées tant que le compte reste actif afin de préserver la progression et la mémoire adaptative. La suppression du compte efface les données gérées par l’application décrites ci-dessus. Les services d’infrastructure et d’IA peuvent conserver séparément des traces opérationnelles ou de sécurité limitées selon leurs politiques.', releaseTitle:'Note de publication', releaseBody:'Cette information intégrée décrit le comportement actuel du produit. Avant un lancement commercial public, la politique publiée devra aussi indiquer l’identité juridique de l’opérateur, les coordonnées de contact et les mentions exigées dans les marchés concernés.'
  },
  German: {
    back:'Zurück', eyebrow:'ENGLISH TWIN · DATENSCHUTZ', title:'Datenschutz & KI-Daten', intro:'Diese Seite erklärt verständlich, welche Daten English Twin speichert, warum sie verwendet werden, wann KI-Dienste Daten erhalten und wie du sie löschen kannst.', scopedTitle:'Deine Lerndaten bleiben deinem Konto zugeordnet.', scopedBody:'Fortschritt, Wiederholungskarten, Verlauf, Fehler, Profileinstellungen, Twin-Gedächtnis und gespeicherte Lernsitzungen werden unter deinem angemeldeten Konto gespeichert. Zugriffsregeln beschränken Nutzerdaten auf dieses Konto.', aiTitle:'AI Twin verwendet begrenzten Lernkontext.', aiBody:'Wenn du AI Twin nutzt, kann die App deine Nachricht zusammen mit einem begrenzten Ausschnitt relevanter Lerninformationen wie jüngsten Fehlern, fälligen Wiederholungen, abgeschlossenen Lektionen und aktuellem Gesprächskontext an den konfigurierten KI-Dienst senden. Passwörter werden nie in KI-Prompts aufgenommen.', voiceTitle:'Sprachfunktionen benötigen eine ausdrückliche Mikrofonfreigabe.', voiceBody:'Live-Sprechen kann Mikrofon-Audio erst nach deiner Zustimmung an den konfigurierten Live-KI-Dienst senden. Das resultierende Transkript und grundlegende Sitzungsdaten können in deinem Konto gespeichert werden, um Fortschritt und spätere Übungen zu unterstützen.', control:'KONTROLLE', choices:'Deine Auswahl', micTitle:'Mikrofonzugriff', micBody:'Du kannst den Mikrofonzugriff ablehnen und alle nicht sprachbasierten Lernmodi weiterverwenden.', aiChoiceTitle:'KI-Funktionen', aiChoiceBody:'Kernlektionen, Wiederholung und deterministische Übungen können getrennt von freiem KI-Chat und Live-Sprechen genutzt werden.', deleteTitle:'Konto und Lerndaten löschen', deleteBody:'Über Profil → Konto löschen kannst du Profil, Lernfortschritt, Wiederholungsverlauf, gespeicherte Fehler, Twin-Gedächtnis, Live-Transkripte und dein Anmeldekonto dauerhaft löschen. Vor der Löschung ist eine aktuelle Anmeldung erforderlich.', retentionTitle:'Aufbewahrung', retentionBody:'Eigene Lerndaten werden gespeichert, solange das Konto aktiv ist, damit English Twin Fortschritt und adaptives Gedächtnis erhalten kann. Die Kontolöschung entfernt die oben genannten App-Daten. Infrastruktur- und KI-Dienste können begrenzte Betriebs- oder Sicherheitsdaten nach ihren eigenen Richtlinien aufbewahren.', releaseTitle:'Veröffentlichungshinweis', releaseBody:'Diese In-App-Erklärung beschreibt das aktuelle Datenverhalten des Produkts. Vor einem öffentlichen kommerziellen Start sollte die veröffentlichte Datenschutzrichtlinie zusätzlich die rechtliche Identität des Betreibers, Kontaktangaben und marktbezogene Pflichtinformationen enthalten.'
  },
  Spanish: {
    back:'Atrás', eyebrow:'ENGLISH TWIN · PRIVACIDAD', title:'Privacidad y datos de IA', intro:'Esta página explica de forma clara qué guarda English Twin, por qué se usa, cuándo los servicios de IA reciben datos y cómo puedes eliminarlos.', scopedTitle:'Tus datos de aprendizaje permanecen vinculados a tu cuenta.', scopedBody:'El progreso, las tarjetas de repaso, el historial, los errores, los ajustes del perfil, la memoria de Twin y las sesiones guardadas se almacenan bajo tu cuenta iniciada. Las reglas de acceso restringen los datos del usuario a esa cuenta.', aiTitle:'AI Twin usa un contexto de aprendizaje limitado.', aiBody:'Cuando usas AI Twin, la aplicación puede enviar tu mensaje junto con una parte limitada del contexto relevante, como errores recientes, repasos pendientes, lecciones completadas y contexto reciente de conversación, al servicio de IA configurado. Las contraseñas nunca se incluyen en los prompts.', voiceTitle:'Las funciones de voz requieren permiso explícito del micrófono.', voiceBody:'La conversación Live puede enviar audio del micrófono al servicio de IA en vivo configurado solo después de que aceptes. La transcripción resultante y metadatos básicos de la sesión pueden guardarse en tu cuenta para apoyar el progreso y la práctica posterior.', control:'CONTROL', choices:'Tus opciones', micTitle:'Acceso al micrófono', micBody:'Puedes rechazar el permiso del micrófono y seguir usando los modos de aprendizaje sin voz.', aiChoiceTitle:'Funciones de IA', aiChoiceBody:'Las lecciones principales, el repaso y la práctica determinista pueden funcionar por separado del chat libre con IA y la conversación Live.', deleteTitle:'Eliminar tu cuenta y datos de aprendizaje', deleteBody:'Desde Perfil → Eliminar cuenta puedes borrar permanentemente tu perfil, progreso, historial de repaso, errores guardados, memoria Twin, transcripciones Live y cuenta de acceso. Se requiere un inicio de sesión reciente antes de comenzar la eliminación.', retentionTitle:'Conservación', retentionBody:'Los registros de aprendizaje del usuario se conservan mientras la cuenta siga activa para mantener el progreso y la memoria adaptativa. Eliminar la cuenta borra los registros gestionados por la aplicación indicados arriba. Los servicios de infraestructura e IA pueden conservar registros operativos o de seguridad limitados según sus propias políticas.', releaseTitle:'Nota de publicación', releaseBody:'Esta información dentro de la aplicación describe el comportamiento actual de los datos. Antes de un lanzamiento comercial público, la política publicada también deberá incluir la identidad legal del operador, datos de contacto y las divulgaciones exigidas en los mercados de lanzamiento.'
  },
};
