import { useEffect, useMemo, useState } from 'react';
import { Navigate, useNavigate } from 'react-router-dom';
import { onAuthStateChanged, User } from 'firebase/auth';
import { doc, getDoc } from 'firebase/firestore';
import { AlertTriangle, Check, ChevronRight, LoaderCircle, LockKeyhole, Star, Target } from 'lucide-react';
import { ETButton, LearningShell, PageTitle, ProgressBar, StatusState, Surface } from './ui/LearningUI';
import { auth, db } from './firebase';
import { lessonsForLevel, lessonsForUnit, unitsForLevel, type LearningLevel } from './curriculumAll';
import { loadLessonProgress, ProgressMap, summarizeProgress } from './learning';
import { directionFor, normalizeLanguage, SupportedLanguage } from './languageSupport';

type Profile = { nativeLanguage?: string; explanationLanguage?: string; interfaceLanguage?: string; currentCurriculumLevel?:string; placementLevel?: string; cefrLevel?: string };
type StateCopy = { loading:string; loadError:string; loadErrorBody:string; retry:string };
const stateCopy: Record<SupportedLanguage, StateCopy> = {
  English:{loading:'Loading your learning path…',loadError:'Couldn’t load your learning path',loadErrorBody:'Your saved lesson progress is still safe. Check the connection and try again.',retry:'Try again'},
  Arabic:{loading:'نحمّل مسار تعلّمك…',loadError:'تعذّر تحميل مسار التعلّم',loadErrorBody:'تقدّم دروسك المحفوظ مازال آمنًا. تحقق من الاتصال وحاول مرة أخرى.',retry:'حاول مرة أخرى'},
  Dutch:{loading:'Je leerpad wordt geladen…',loadError:'Je leerpad kon niet worden geladen',loadErrorBody:'Je opgeslagen lesvoortgang is veilig. Controleer je verbinding en probeer opnieuw.',retry:'Opnieuw proberen'},
  French:{loading:'Chargement de ton parcours…',loadError:'Impossible de charger ton parcours',loadErrorBody:'Ta progression enregistrée est intacte. Vérifie la connexion et réessaie.',retry:'Réessayer'},
  German:{loading:'Dein Lernpfad wird geladen…',loadError:'Dein Lernpfad konnte nicht geladen werden',loadErrorBody:'Dein gespeicherter Fortschritt ist sicher. Prüfe die Verbindung und versuche es erneut.',retry:'Erneut versuchen'},
  Spanish:{loading:'Cargando tu ruta de aprendizaje…',loadError:'No se pudo cargar tu ruta',loadErrorBody:'Tu progreso guardado sigue seguro. Revisa la conexión y vuelve a intentarlo.',retry:'Intentar de nuevo'},
};
const supportedLevels: LearningLevel[] = ['A1','A2','B1','B2','C1'];
function normalizedLearningLevel(value?: string): LearningLevel { const upper=String(value||'A1').toUpperCase(); return supportedLevels.includes(upper as LearningLevel)?upper as LearningLevel:'A1'; }
function levelTitle(level: LearningLevel, ar: boolean) { if(ar){if(level==='A1')return'الأساسيات';if(level==='A2')return'الاستقلال اليومي';if(level==='B1')return'تواصل مستقل';if(level==='B2')return'نقاش وتفكير متقدم';return'دقة ومرونة متقدمة';}if(level==='A1')return'Foundations';if(level==='A2')return'Real-world independence';if(level==='B1')return'Independent communication';if(level==='B2')return'Complex communication & argument';return'Advanced precision & synthesis'; }

export default function ReferenceLearnJourney() {
  const nav=useNavigate();const[user,setUser]=useState<User|null>(null);const[profile,setProfile]=useState<Profile>({});const[progress,setProgress]=useState<ProgressMap>({});const[loading,setLoading]=useState(true);const[loadError,setLoadError]=useState(false);const[reloadKey,setReloadKey]=useState(0);const[level,setLevel]=useState<LearningLevel>('A1');
  useEffect(()=>{const unsubscribe=onAuthStateChanged(auth,async current=>{setUser(current);setLoadError(false);setLoading(true);if(!current){setLoading(false);return;}try{const[profileSnap,learnerProgress]=await Promise.all([getDoc(doc(db,'users',current.uid)),loadLessonProgress(current.uid)]);const nextProfile=profileSnap.exists()?profileSnap.data() as Profile:{};setProfile(nextProfile);setProgress(learnerProgress);setLevel(normalizedLearningLevel(nextProfile.currentCurriculumLevel||nextProfile.placementLevel||nextProfile.cefrLevel));}catch{setLoadError(true);}finally{setLoading(false);}});return unsubscribe;},[reloadKey]);
  const language=normalizeLanguage(profile.explanationLanguage||profile.nativeLanguage||profile.interfaceLanguage||'English');const dir=directionFor(language);const ar=language==='Arabic';const state=stateCopy[language];const levelLessons=useMemo(()=>lessonsForLevel(level),[level]);const summary=useMemo(()=>summarizeProgress(progress,levelLessons.length),[progress,levelLessons]);const levelUnits=useMemo(()=>unitsForLevel(level),[level]);
  function lessonUnlocked(lessonId:string){const levelIndex=levelLessons.findIndex(lesson=>lesson.id===lessonId);if(levelIndex<0)return false;if(progress[lessonId]?.completed||levelIndex===0)return true;const previous=levelLessons[levelIndex-1];return Boolean(previous&&progress[previous.id]?.completed);}
  if(loading)return <LearningShell language={language} dir={dir} showDock={false}><StatusState icon={<LoaderCircle/>} eyebrow="ENGLISH TWIN" title={state.loading}/></LearningShell>;
  if(!user)return <Navigate to="/welcome" replace/>;
  if(loadError)return <LearningShell language={language} dir={dir} showDock={false}><StatusState icon={<AlertTriangle/>} tone="danger" title={state.loadError} body={state.loadErrorBody} action={<ETButton onClick={()=>setReloadKey(value=>value+1)}>{state.retry}</ETButton>}/></LearningShell>;
  return <LearningShell language={language} dir={dir} className="et-learn-shell">
    <PageTitle title={ar?'تعلّم':'Learn'} description={ar?'مسار متدرج من الأساسيات إلى الفهم والنقاش المتقدم.':'A progressive path from foundations to advanced comprehension, synthesis and communication.'}/>
    <div className="et-cefr-tabs" role="tablist" aria-label="CEFR level"><button type="button" onClick={()=>nav('/start')}>A0</button>{supportedLevels.map(item=><button key={item} type="button" className={level===item?'active':''} onClick={()=>setLevel(item)} aria-selected={level===item} role="tab">{item}</button>)}</div>
    <Surface className="et-level-summary"><div className="et-level-summary-head"><div><span>{level}</span><h2>{levelTitle(level,ar)}</h2></div><strong>{summary.percent}%</strong></div><ProgressBar value={summary.percent}/><small>{ar?`أكملت ${summary.completed} من ${summary.total} درسًا`:`${summary.completed} of ${summary.total} lessons completed`}</small></Surface>
    {summary.percent===100?<Surface className="et-level-checkpoint-cta" tone="teal"><div><Target/><div><b>{ar?`افحص جاهزية ${level}`:`Check ${level} readiness`}</b><p>{ar?'إكمال الدروس يفتح فحص الأدلة عبر المهارات؛ الترقية لا تعتمد على عدد الدروس فقط.':'Lesson completion unlocks the evidence checkpoint; level advancement is not based on lesson count alone.'}</p></div></div><ETButton onClick={()=>nav('/checkpoint')}>{ar?'فتح فحص المستوى':'Open level checkpoint'}<ChevronRight/></ETButton></Surface>:null}
    <div className="et-learning-path">{levelUnits.map((unit,unitIndex)=>{const unitLessons=lessonsForUnit(unit.id);const completeCount=unitLessons.filter(lesson=>progress[lesson.id]?.completed).length;const firstOpen=unitLessons.find(lesson=>!progress[lesson.id]?.completed&&lessonUnlocked(lesson.id));const unitComplete=unitLessons.length>0&&completeCount===unitLessons.length;return <section className="et-unit" key={unit.id}><div className="et-unit-rail" aria-hidden="true"><span>{unitIndex+1}</span><i/></div><div className="et-unit-content"><div className="et-unit-title"><small>{level} · {ar?'الوحدة':'UNIT'} {String(unitIndex+1).padStart(2,'0')}</small><h2>{unit.title.replace(/^(A1|A2|B1|B2|C1) · /,'')}</h2><p>{ar?`${completeCount} من ${unitLessons.length} دروس مكتملة`:`${completeCount} of ${unitLessons.length} lessons complete`}</p></div><Surface className="et-lesson-list">{unitLessons.map((lesson,lessonIndex)=>{const result=progress[lesson.id];const complete=Boolean(result?.completed);const unlocked=lessonUnlocked(lesson.id);return <button type="button" key={lesson.id} className={`et-lesson-row ${complete?'complete':unlocked?'current':'locked'}`} onClick={()=>unlocked&&nav(`/lesson/${lesson.id}`)} disabled={!unlocked} aria-label={`${lesson.title}. ${complete?'Completed':unlocked?'Available':'Locked'}.`}><span className="et-lesson-node">{complete?<Check/>:unlocked?lessonIndex+1:<LockKeyhole/>}</span><div><b>{lesson.title}</b><small>{lesson.skill} · {lesson.minutes} min</small></div><span className="et-lesson-status">{complete?`${result?.score??100}%`:unlocked?(ar?'ابدأ':'Start'):''}{unlocked&&!complete?<ChevronRight/>:null}</span></button>})}</Surface><div className="et-unit-reward"><Star/><div><b>{ar?`تقدّم في ${level}`:`${level} progress`}</b><small>{unitComplete?(ar?'اكتملت هذه الوحدة.':'This unit is complete.'):(ar?'كل درس يفتح الخطوة التالية داخل هذا المستوى.':'Each lesson unlocks the next step in this level.')}</small></div><ETButton variant="ghost" disabled={!firstOpen} aria-label={firstOpen?`Open ${firstOpen.title}`:'No available lesson'} onClick={()=>firstOpen&&nav(`/lesson/${firstOpen.id}`)}>{unitComplete?<Check/>:<ChevronRight/>}</ETButton></div></div></section>})}</div>
  </LearningShell>;
}
