import { useEffect, useMemo, useState } from 'react';
import { Navigate, NavLink, useNavigate } from 'react-router-dom';
import { onAuthStateChanged, User } from 'firebase/auth';
import { doc, getDoc } from 'firebase/firestore';
import { BookOpen, ChevronRight, Crown, Gauge, Home, Mic, RotateCcw, Sparkles, Trophy, UserRound } from 'lucide-react';
import { auth, db } from './firebase';
import { lessons, lessonsForLevel } from './curriculumAll';
import { loadLessonProgress, ProgressMap, summarizeProgress } from './learning';
import { dueCards, ensureReviewCards } from './review';
import { buildDailyPlan, SkillLevels, weakestMeasuredSkill } from './adaptiveLearning';
import { directionFor, normalizeLanguage } from './languageSupport';

type Profile={displayName?:string;learningGoal?:string;dailyTargetMinutes?:number;onboardingCompleted?:boolean;beginnerFoundationCompleted?:boolean;nativeLanguage?:string;explanationLanguage?:string;interfaceLanguage?:string;placementLevel?:string;skillLevels?:Partial<SkillLevels>};
type Recommendation={kind:'foundation'|'review'|'lesson'|'speak';eyebrow:string;title:string;body:string;action:string;to:string};
const arCopy={home:'الرئيسية',learn:'تعلّم',practice:'تدريب',speak:'تحدث',me:'أنا',loading:'نقرأ حالة تعلّمك…',morning:'مرحبًا',amazing:'خلّينا نخلي اليوم رائعًا!',goal:'هدف اليوم',progress:'تقدم ممتاز!',continue:'تابع التعلّم',plan:'خطة اليوم',review:'مراجعة المفردات',twin:'تحدث مع Twin',smart:'المراجعة الذكية',start:'ابدأ الكلمات الأولى',due:'مستحق للمراجعة'};
function Dock({ar}:{ar:boolean}){const labels=ar?[arCopy.home,arCopy.learn,arCopy.practice,arCopy.speak,arCopy.me]:['Home','Learn','Practice','Speak','Me'];return <nav className="dock">{[['/',Home],['/learn',BookOpen],['/practice',Gauge],['/speak',Mic],['/profile',UserRound]].map(([to,Icon]:any,i)=><NavLink end={to==='/'} key={to} to={to}><Icon/><small>{labels[i]}</small></NavLink>)}</nav>}
export default function SmartHomeV2(){
 const nav=useNavigate();const[user,setUser]=useState<User|null>(null);const[profile,setProfile]=useState<Profile|null>(null);const[progress,setProgress]=useState<ProgressMap>({});const[dueCount,setDueCount]=useState(0);const[loading,setLoading]=useState(true);
 useEffect(()=>onAuthStateChanged(auth,async current=>{setLoading(true);setUser(current);if(!current){setProfile(null);setProgress({});setDueCount(0);setLoading(false);return}try{const[snap,p]=await Promise.all([getDoc(doc(db,'users',current.uid)),loadLessonProgress(current.uid)]);const next=snap.exists()?snap.data() as Profile:{};setProfile(next);setProgress(p);const completed=Object.values(p).filter(x=>x.completed).map(x=>x.lessonId);const cards=await ensureReviewCards(current.uid,completed);setDueCount(dueCards(cards).length)}catch{setDueCount(0)}finally{setLoading(false)}}),[]);
 const support=normalizeLanguage(profile?.explanationLanguage||profile?.nativeLanguage||profile?.interfaceLanguage);const ar=support==='Arabic';const dir=directionFor(support);const nextLesson=useMemo(()=>lessons.find(l=>!progress[l.id]?.completed),[progress]);const weakestSkill=useMemo(()=>weakestMeasuredSkill(profile?.skillLevels),[profile?.skillLevels]);const dailyPlan=useMemo(()=>buildDailyPlan({dailyTargetMinutes:profile?.dailyTargetMinutes||15,dueReviews:dueCount,nextLessonId:nextLesson?.id,weakestSkill,speakingAvailable:true}),[profile?.dailyTargetMinutes,dueCount,nextLesson?.id,weakestSkill]);const a1=useMemo(()=>summarizeProgress(progress,lessonsForLevel('A1').length),[progress]);const target=profile?.dailyTargetMinutes||15;
 const recommendation:Recommendation=useMemo(()=>{if(!profile?.beginnerFoundationCompleted)return{kind:'foundation',eyebrow:'A0 → A1',title:ar?'كلماتك الأولى':'Your first words',body:ar?'صور، استماع، نطق ومعنى في خطوات قصيرة.':'Pictures, listening, pronunciation and meaning in short steps.',action:ar?arCopy.start:'Start first words',to:'/start'};if(dueCount)return{kind:'review',eyebrow:ar?arCopy.due:'SMART REVIEW',title:ar?`${dueCount} بطاقات تنتظرك`:`${dueCount} cards are ready`,body:ar?'ثبّت الكلمات في ذاكرتك قبل الدرس التالي.':'Lock them into memory before your next lesson.',action:ar?'راجع الآن':'Review now',to:'/review'};if(nextLesson)return{kind:'lesson',eyebrow:nextLesson.id.startsWith('a2-')?'A2':'A1',title:nextLesson.title,body:ar?'الخطوة التالية الأنسب لك اليوم.':nextLesson.objective,action:ar?'تابع الدرس':'Continue lesson',to:`/lesson/${nextLesson.id}`};return{kind:'speak',eyebrow:'LIVE',title:ar?'حان وقت الكلام':'Time to speak',body:ar?'حوّل ما تعلمته إلى محادثة حقيقية.':'Turn what you learned into a real conversation.',action:ar?'ابدأ المحادثة':'Start speaking',to:'/speak'}},[profile?.beginnerFoundationCompleted,dueCount,nextLesson,ar]);
 function planRoute(id:string,lessonId?:string){if(id==='review')return'/review';if(id==='lesson'&&lessonId)return`/lesson/${lessonId}`;if(id==='speaking')return'/speak';return'/practice'}
 if(loading)return <main className="center wake" dir={dir}><Sparkles/><p>{ar?arCopy.loading:'Reading your learning state…'}</p></main>;if(!user)return <Navigate to="/welcome" replace/>;if(!profile?.onboardingCompleted||!profile?.nativeLanguage)return <Navigate to="/setup" replace/>;
 const name=profile.displayName||user.displayName||'Learner';
 return <div className="app-shell reference-home" dir={dir}><div className="phone"><main className="page"><header className="home-header reference-header"><div><span className="brand-wordmark">English <b>Twin</b><i>✦</i></span><small>AI Language Coach</small></div><button className="icon crown-button" onClick={()=>nav('/profile')}><Crown/></button></header>
 <section className="welcome-card"><div><small>{ar?arCopy.morning:'Good morning,'}</small><h1>{name}! 👋</h1><p>{ar?arCopy.amazing:"Let's make today amazing!"}</p></div><div className="mini-twin" aria-hidden="true"><span/><i/><b>⌣</b></div></section>
 <section className="goal-card"><div className="goal-title"><div><b>{ar?arCopy.goal:'Daily goal'}</b><span>{target} min</span></div></div><div className="goal-content"><div className="goal-ring" style={{'--goal':`${Math.max(8,a1.percent)}%`} as any}><strong>{a1.percent}%</strong></div><p>{ar?arCopy.progress:'Great progress!'} 🎉</p><Sparkles/></div></section>
 <section className="continue-card"><div className="continue-copy"><span>{ar?arCopy.continue:'Continue learning'}</span><small>{recommendation.eyebrow}</small><h2>{recommendation.title}</h2><p>{recommendation.body}</p><div className="continue-progress"><i style={{width:`${Math.max(8,a1.percent)}%`}}/></div><button onClick={()=>nav(recommendation.to)}>{recommendation.kind==='review'?<RotateCcw/>:recommendation.kind==='speak'?<Mic/>:<BookOpen/>}{recommendation.action}<ChevronRight/></button></div><div className="continue-art"><div className="sun"/><div className="umbrella">☂</div><div className="table">▰</div><span>✦</span></div></section>
 <section><div className="section-heading reference-section"><h3>{ar?arCopy.plan:"Today's plan"}</h3><button onClick={()=>nav('/learn')}>{ar?'عرض الكل':'See all'}</button></div><div className="today-list">{(!profile.beginnerFoundationCompleted?[{id:'foundation',minutes:target,reason:'',lessonId:undefined}]:dailyPlan.slice(0,3)).map((item:any,index)=><button key={`${item.id}-${index}`} onClick={()=>nav(item.id==='foundation'?'/start':planRoute(item.id,item.lessonId))}><span className={`plan-icon plan-${index}`}>{index===0?<BookOpen/>:index===1?<Mic/>:<RotateCcw/>}</span><div><b>{item.id==='foundation'?(ar?arCopy.start:'First words'):item.id==='review'?(ar?arCopy.review:'Vocabulary Review'):item.id==='speaking'?(ar?arCopy.twin:'Speak with Twin'):item.id==='lesson'?(ar?'الدرس التالي':'Next lesson'):(ar?arCopy.smart:'Smart Review')}</b><small>{item.minutes||target} min</small></div><ChevronRight/></button>)}</div></section>
 <section className="home-reward"><Trophy/><div><b>{ar?'استمر!':'Keep it going!'}</b><small>{ar?'كل خطوة صغيرة تبني إنجليزية أقوى.':'Every small step builds stronger English.'}</small></div><button onClick={()=>nav('/practice')}>{ar?'تدرّب':'Practice'}</button></section>
 </main><Dock ar={ar}/></div></div>;
}