import { useEffect, useMemo, useState } from 'react';
import { Navigate, useNavigate } from 'react-router-dom';
import { onAuthStateChanged, User } from 'firebase/auth';
import { doc, getDoc } from 'firebase/firestore';
import { BookOpen, ChevronRight, Crown, Mic, RotateCcw, Sparkles, Trophy } from 'lucide-react';
import AppDock from './AppDock';
import { auth, db } from './firebase';
import { lessons, lessonsForLevel } from './curriculumAll';
import { loadLessonProgress, ProgressMap, summarizeProgress } from './learning';
import { dueCards, ensureReviewCards } from './review';
import { buildDailyPlan, SkillLevels, weakestMeasuredSkill } from './adaptiveLearning';
import { directionFor, normalizeLanguage, SupportedLanguage, t } from './languageSupport';

type Profile={displayName?:string;learningGoal?:string;dailyTargetMinutes?:number;onboardingCompleted?:boolean;beginnerFoundationCompleted?:boolean;nativeLanguage?:string;explanationLanguage?:string;interfaceLanguage?:string;placementLevel?:string;skillLevels?:Partial<SkillLevels>};
type Recommendation={kind:'foundation'|'review'|'lesson'|'speak';eyebrow:string;title:string;body:string;action:string;to:string};

const recommendationCopy: Record<SupportedLanguage, { foundationBody:string; due:string; cardsReady:string; reviewBody:string; nextBody:string; continueLesson:string; speakTitle:string; speakBody:string; startSpeaking:string }> = {
 English:{foundationBody:'Pictures, listening, pronunciation and meaning in short steps.',due:'SMART REVIEW',cardsReady:'cards are ready',reviewBody:'Lock them into memory before your next lesson.',nextBody:'The best next step for you today.',continueLesson:'Continue lesson',speakTitle:'Time to speak',speakBody:'Turn what you learned into a real conversation.',startSpeaking:'Start speaking'},
 Arabic:{foundationBody:'صور، استماع، نطق ومعنى في خطوات قصيرة.',due:'مستحق للمراجعة',cardsReady:'بطاقات تنتظرك',reviewBody:'ثبّت الكلمات في ذاكرتك قبل الدرس التالي.',nextBody:'الخطوة التالية الأنسب لك اليوم.',continueLesson:'تابع الدرس',speakTitle:'حان وقت الكلام',speakBody:'حوّل ما تعلمته إلى محادثة حقيقية.',startSpeaking:'ابدأ المحادثة'},
 Dutch:{foundationBody:'Afbeeldingen, luisteren, uitspraak en betekenis in korte stappen.',due:'SLIM HERHALEN',cardsReady:'kaarten staan klaar',reviewBody:'Zet ze vast in je geheugen vóór je volgende les.',nextBody:'De beste volgende stap voor vandaag.',continueLesson:'Ga verder met de les',speakTitle:'Tijd om te spreken',speakBody:'Zet wat je hebt geleerd om in een echt gesprek.',startSpeaking:'Begin met spreken'},
 French:{foundationBody:'Images, écoute, prononciation et sens en petites étapes.',due:'RÉVISION INTELLIGENTE',cardsReady:'cartes sont prêtes',reviewBody:'Fixe-les en mémoire avant ta prochaine leçon.',nextBody:'La meilleure prochaine étape pour aujourd’hui.',continueLesson:'Continuer la leçon',speakTitle:'À toi de parler',speakBody:'Transforme ce que tu as appris en vraie conversation.',startSpeaking:'Commencer à parler'},
 German:{foundationBody:'Bilder, Hören, Aussprache und Bedeutung in kurzen Schritten.',due:'INTELLIGENTE WIEDERHOLUNG',cardsReady:'Karten sind bereit',reviewBody:'Festige sie vor deiner nächsten Lektion im Gedächtnis.',nextBody:'Der beste nächste Schritt für heute.',continueLesson:'Lektion fortsetzen',speakTitle:'Zeit zu sprechen',speakBody:'Mach aus dem Gelernten ein echtes Gespräch.',startSpeaking:'Sprechen starten'},
 Spanish:{foundationBody:'Imágenes, escucha, pronunciación y significado en pasos cortos.',due:'REPASO INTELIGENTE',cardsReady:'tarjetas están listas',reviewBody:'Fíjalas en la memoria antes de tu próxima lección.',nextBody:'El mejor siguiente paso para hoy.',continueLesson:'Continuar lección',speakTitle:'Hora de hablar',speakBody:'Convierte lo aprendido en una conversación real.',startSpeaking:'Empezar a hablar'},
};

export default function SmartHomeV2(){
 const nav=useNavigate();const[user,setUser]=useState<User|null>(null);const[profile,setProfile]=useState<Profile|null>(null);const[progress,setProgress]=useState<ProgressMap>({});const[dueCount,setDueCount]=useState(0);const[loading,setLoading]=useState(true);
 useEffect(()=>onAuthStateChanged(auth,async current=>{setLoading(true);setUser(current);if(!current){setProfile(null);setProgress({});setDueCount(0);setLoading(false);return}try{const[snap,p]=await Promise.all([getDoc(doc(db,'users',current.uid)),loadLessonProgress(current.uid)]);const next=snap.exists()?snap.data() as Profile:{};setProfile(next);setProgress(p);const completed=Object.values(p).filter(x=>x.completed).map(x=>x.lessonId);const cards=await ensureReviewCards(current.uid,completed);setDueCount(dueCards(cards).length)}catch{setDueCount(0)}finally{setLoading(false)}}),[]);
 const support=normalizeLanguage(profile?.explanationLanguage||profile?.nativeLanguage||profile?.interfaceLanguage);const dir=directionFor(support);const copy=recommendationCopy[support];const nextLesson=useMemo(()=>lessons.find(l=>!progress[l.id]?.completed),[progress]);const weakestSkill=useMemo(()=>weakestMeasuredSkill(profile?.skillLevels),[profile?.skillLevels]);const dailyPlan=useMemo(()=>buildDailyPlan({dailyTargetMinutes:profile?.dailyTargetMinutes||15,dueReviews:dueCount,nextLessonId:nextLesson?.id,weakestSkill,speakingAvailable:true}),[profile?.dailyTargetMinutes,dueCount,nextLesson?.id,weakestSkill]);const a1=useMemo(()=>summarizeProgress(progress,lessonsForLevel('A1').length),[progress]);const target=profile?.dailyTargetMinutes||15;
 const recommendation:Recommendation=useMemo(()=>{if(!profile?.beginnerFoundationCompleted)return{kind:'foundation',eyebrow:'A0 → A1',title:t(support,'firstWords'),body:copy.foundationBody,action:t(support,'startFirstWords'),to:'/start'};if(dueCount)return{kind:'review',eyebrow:copy.due,title:`${dueCount} ${copy.cardsReady}`,body:copy.reviewBody,action:t(support,'reviewNow'),to:'/review'};if(nextLesson)return{kind:'lesson',eyebrow:nextLesson.id.startsWith('a2-')?'A2':'A1',title:nextLesson.title,body:copy.nextBody,action:copy.continueLesson,to:`/lesson/${nextLesson.id}`};return{kind:'speak',eyebrow:'LIVE',title:copy.speakTitle,body:copy.speakBody,action:copy.startSpeaking,to:'/speak'}},[profile?.beginnerFoundationCompleted,dueCount,nextLesson,support,copy]);
 function planRoute(id:string,lessonId?:string){if(id==='review')return'/review';if(id==='lesson'&&lessonId)return`/lesson/${lessonId}`;if(id==='speaking')return'/speak';return'/practice'}
 if(loading)return <main className="center wake" dir={dir}><Sparkles/><p>{t(support,'loadingState')}</p></main>;if(!user)return <Navigate to="/welcome" replace/>;if(!profile?.onboardingCompleted||!profile?.nativeLanguage)return <Navigate to="/setup" replace/>;
 const name=profile.displayName||user.displayName||'Learner';
 return <div className="app-shell reference-home" dir={dir}><div className="phone"><main className="page"><header className="home-header reference-header"><div><span className="brand-wordmark">English <b>Twin</b><i>✦</i></span><small>AI Language Coach</small></div><button className="icon crown-button" onClick={()=>nav('/profile')}><Crown/></button></header>
 <section className="welcome-card"><div><small>{t(support,'greeting')}</small><h1>{name}! 👋</h1><p>{t(support,'amazing')}</p></div><div className="mini-twin" aria-hidden="true"><span/><i/><b>⌣</b></div></section>
 <section className="goal-card"><div className="goal-title"><div><b>{t(support,'dailyGoal')}</b><span>{target} min</span></div></div><div className="goal-content"><div className="goal-ring" style={{'--goal':`${Math.max(8,a1.percent)}%`} as any}><strong>{a1.percent}%</strong></div><p>{t(support,'greatProgress')} 🎉</p><Sparkles/></div></section>
 <section className="continue-card"><div className="continue-copy"><span>{t(support,'continueLearning')}</span><small>{recommendation.eyebrow}</small><h2>{recommendation.title}</h2><p>{recommendation.body}</p><div className="continue-progress"><i style={{width:`${Math.max(8,a1.percent)}%`}}/></div><button onClick={()=>nav(recommendation.to)}>{recommendation.kind==='review'?<RotateCcw/>:recommendation.kind==='speak'?<Mic/>:<BookOpen/>}{recommendation.action}<ChevronRight/></button></div><div className="continue-art"><div className="sun"/><div className="umbrella">☂</div><div className="table">▰</div><span>✦</span></div></section>
 <section><div className="section-heading reference-section"><h3>{t(support,'todayPlan')}</h3><button onClick={()=>nav('/learn')}>{t(support,'seeAll')}</button></div><div className="today-list">{(!profile.beginnerFoundationCompleted?[{id:'foundation',minutes:target,reason:'',lessonId:undefined}]:dailyPlan.slice(0,3)).map((item:any,index)=><button key={`${item.id}-${index}`} onClick={()=>nav(item.id==='foundation'?'/start':planRoute(item.id,item.lessonId))}><span className={`plan-icon plan-${index}`}>{index===0?<BookOpen/>:index===1?<Mic/>:<RotateCcw/>}</span><div><b>{item.id==='foundation'?t(support,'startFirstWords'):item.id==='review'?t(support,'vocabularyReview'):item.id==='speaking'?t(support,'speakWithTwin'):item.id==='lesson'?t(support,'nextLesson'):t(support,'smartReview')}</b><small>{item.minutes||target} min</small></div><ChevronRight/></button>)}</div></section>
 <section className="home-reward"><Trophy/><div><b>{t(support,'keepGoing')}</b><small>{t(support,'keepGoingBody')}</small></div><button onClick={()=>nav('/practice')}>{t(support,'practice')}</button></section>
 </main><AppDock language={support}/></div></div>;
}