import { SupportedLanguage } from './languageSupport';

type SpeechSupportCopy = {
  home: string;
  loading: string;
  noDrills: string;
  recognitionUnsupported: string;
  micError: (error: string) => string;
  eyebrow: string;
  title: string;
  intro: string;
  privacyEyebrow: string;
  consentTitle: string;
  consentBody: string;
  notNow: string;
  acceptStart: string;
  hearTarget: string;
  reset: string;
  speakNow: string;
  listening: string;
  heard: string;
  accuracy: string;
  excellent: string;
  good: string;
  retry: string;
  missing: string;
  extra: string;
  nextDrill: string;
  freeConversation: string;
  readyNatural: string;
  liveBody: string;
  openLive: string;
};

export const speechSupportCopy: Record<SupportedLanguage, SpeechSupportCopy> = {
  English:{home:'Home',loading:'Preparing speech practice…',noDrills:'No speaking drills are available yet.',recognitionUnsupported:'Guided speech recognition is not supported in this browser. Use Live Conversation instead.',micError:error=>`Microphone recognition error: ${error}`,eyebrow:'GUIDED SPEECH · ADAPTIVE',title:'Say it clearly',intro:'Practice real lesson sentences. Weak lessons are prioritized from your saved mistake history.',privacyEyebrow:'MICROPHONE PRIVACY',consentTitle:'Before speech recognition starts',consentBody:"Your browser's speech-recognition service may process microphone audio to produce text. English Twin does not store raw audio from Guided Speech. It stores the recognized transcript, accuracy score, and learning mistakes in your account when needed for adaptive practice.",notNow:'Not now',acceptStart:'I understand · Start',hearTarget:'Hear target',reset:'Reset',speakNow:'Speak now',listening:'Listening…',heard:'WHAT WE HEARD',accuracy:'SPEECH ACCURACY',excellent:'Excellent match',good:'Good — one more clean repetition',retry:'Try again',missing:'Missing / unclear',extra:'Extra words heard',nextDrill:'Next drill',freeConversation:'FREE CONVERSATION',readyNatural:'Ready to speak naturally?',liveBody:'Live Conversation uses your authenticated English Twin voice session for open-ended dialogue.',openLive:'Open Live'},
  Arabic:{home:'الرئيسية',loading:'نجهّز تدريب النطق…',noDrills:'لا توجد تمارين نطق متاحة الآن.',recognitionUnsupported:'التعرّف الموجّه على الكلام غير مدعوم في هذا المتصفح. استخدم المحادثة المباشرة بدلًا منه.',micError:error=>`خطأ في التعرّف عبر الميكروفون: ${error}`,eyebrow:'تدريب نطق · متكيّف',title:'قلها بوضوح',intro:'تدرّب على جمل حقيقية من الدروس. نعطي الأولوية للدروس الأضعف حسب سجل أخطائك.',privacyEyebrow:'خصوصية الميكروفون',consentTitle:'قبل بدء التعرّف على الكلام',consentBody:'قد تعالج خدمة التعرّف على الكلام في متصفحك صوت الميكروفون لتحويله إلى نص. لا يخزن English Twin الصوت الخام في Guided Speech. عند الحاجة للتعلم المتكيّف، يخزن النص المتعرّف عليه ودرجة الدقة والأخطاء التعليمية في حسابك.',notNow:'ليس الآن',acceptStart:'فهمت · ابدأ',hearTarget:'اسمع الجملة',reset:'إعادة',speakNow:'تحدث الآن',listening:'أستمع…',heard:'ما تم سماعه',accuracy:'دقة النطق',excellent:'مطابقة ممتازة',good:'جيد — كررها مرة نظيفة',retry:'حاول مرة أخرى',missing:'كلمات ناقصة / غير واضحة',extra:'كلمات إضافية تم سماعها',nextDrill:'التمرين التالي',freeConversation:'محادثة حرة',readyNatural:'جاهز للكلام بشكل طبيعي؟',liveBody:'المحادثة المباشرة تستخدم جلسة English Twin الصوتية الموثقة لحوار مفتوح.',openLive:'افتح المحادثة المباشرة'},
  Dutch:{home:'Home',loading:'Spraakoefening wordt voorbereid…',noDrills:'Er zijn nog geen spreekoefeningen beschikbaar.',recognitionUnsupported:'Begeleide spraakherkenning wordt niet ondersteund in deze browser. Gebruik Live Conversation.',micError:error=>`Fout bij microfoonherkenning: ${error}`,eyebrow:'BEGELEID SPREKEN · ADAPTIEF',title:'Zeg het duidelijk',intro:'Oefen echte zinnen uit je lessen. Zwakke lessen krijgen voorrang op basis van je opgeslagen fouten.',privacyEyebrow:'MICROFOONPRIVACY',consentTitle:'Voordat spraakherkenning start',consentBody:'De spraakherkenningsdienst van je browser kan microfoonaudio verwerken om tekst te maken. English Twin slaat bij Guided Speech geen ruwe audio op. Voor adaptieve oefening kunnen de herkende tekst, nauwkeurigheidsscore en leerfouten in je account worden opgeslagen.',notNow:'Niet nu',acceptStart:'Ik begrijp het · Start',hearTarget:'Luister naar doelzin',reset:'Opnieuw',speakNow:'Spreek nu',listening:'Luisteren…',heard:'WAT WE HOORDEN',accuracy:'SPRAAKNAUWKEURIGHEID',excellent:'Uitstekende match',good:'Goed — nog één duidelijke herhaling',retry:'Probeer opnieuw',missing:'Ontbrekend / onduidelijk',extra:'Extra woorden gehoord',nextDrill:'Volgende oefening',freeConversation:'VRIJ GESPREK',readyNatural:'Klaar om natuurlijk te spreken?',liveBody:'Live Conversation gebruikt je beveiligde English Twin-spraaksessie voor een open gesprek.',openLive:'Live openen'},
  French:{home:'Accueil',loading:'Préparation de l’exercice oral…',noDrills:'Aucun exercice oral n’est disponible pour le moment.',recognitionUnsupported:'La reconnaissance vocale guidée n’est pas prise en charge par ce navigateur. Utilise la conversation en direct.',micError:error=>`Erreur de reconnaissance du microphone : ${error}`,eyebrow:'ORAL GUIDÉ · ADAPTATIF',title:'Dis-le clairement',intro:'Entraîne-toi avec de vraies phrases de tes leçons. Les leçons faibles passent en priorité selon tes erreurs enregistrées.',privacyEyebrow:'CONFIDENTIALITÉ DU MICROPHONE',consentTitle:'Avant de démarrer la reconnaissance vocale',consentBody:'Le service de reconnaissance vocale de ton navigateur peut traiter le son du microphone pour produire du texte. English Twin ne stocke pas l’audio brut de Guided Speech. Le texte reconnu, le score de précision et les erreurs d’apprentissage peuvent être enregistrés dans ton compte pour la pratique adaptative.',notNow:'Pas maintenant',acceptStart:'J’ai compris · Démarrer',hearTarget:'Écouter la phrase',reset:'Réinitialiser',speakNow:'Parler maintenant',listening:'Écoute…',heard:'CE QUI A ÉTÉ ENTENDU',accuracy:'PRÉCISION ORALE',excellent:'Excellente correspondance',good:'Bien — encore une répétition claire',retry:'Réessayer',missing:'Manquant / peu clair',extra:'Mots supplémentaires entendus',nextDrill:'Exercice suivant',freeConversation:'CONVERSATION LIBRE',readyNatural:'Prêt à parler naturellement ?',liveBody:'La conversation en direct utilise ta session vocale English Twin authentifiée pour un dialogue ouvert.',openLive:'Ouvrir Live'},
  German:{home:'Start',loading:'Sprechtraining wird vorbereitet…',noDrills:'Noch keine Sprechübungen verfügbar.',recognitionUnsupported:'Geführte Spracherkennung wird in diesem Browser nicht unterstützt. Nutze stattdessen Live Conversation.',micError:error=>`Fehler bei der Mikrofonerkennung: ${error}`,eyebrow:'GEFÜHRTES SPRECHEN · ADAPTIV',title:'Sag es deutlich',intro:'Übe echte Sätze aus deinen Lektionen. Schwächere Lektionen werden anhand deiner gespeicherten Fehler priorisiert.',privacyEyebrow:'MIKROFON-DATENSCHUTZ',consentTitle:'Bevor die Spracherkennung startet',consentBody:'Der Spracherkennungsdienst deines Browsers kann Mikrofonaudio in Text umwandeln. English Twin speichert bei Guided Speech kein Roh-Audio. Erkannter Text, Genauigkeitswert und Lernfehler können für adaptive Übungen in deinem Konto gespeichert werden.',notNow:'Nicht jetzt',acceptStart:'Verstanden · Starten',hearTarget:'Zielsatz anhören',reset:'Zurücksetzen',speakNow:'Jetzt sprechen',listening:'Hört zu…',heard:'WAS ERKANNT WURDE',accuracy:'SPRECHGENAUIGKEIT',excellent:'Ausgezeichnete Übereinstimmung',good:'Gut — noch eine saubere Wiederholung',retry:'Nochmal versuchen',missing:'Fehlend / unklar',extra:'Zusätzliche Wörter erkannt',nextDrill:'Nächste Übung',freeConversation:'FREIES GESPRÄCH',readyNatural:'Bereit, natürlich zu sprechen?',liveBody:'Live Conversation nutzt deine authentifizierte English Twin-Sprachsitzung für einen offenen Dialog.',openLive:'Live öffnen'},
  Spanish:{home:'Inicio',loading:'Preparando la práctica oral…',noDrills:'Todavía no hay ejercicios de pronunciación disponibles.',recognitionUnsupported:'El reconocimiento guiado de voz no es compatible con este navegador. Usa la conversación en directo.',micError:error=>`Error de reconocimiento del micrófono: ${error}`,eyebrow:'PRÁCTICA ORAL · ADAPTATIVA',title:'Dilo con claridad',intro:'Practica frases reales de tus lecciones. Las lecciones más débiles tienen prioridad según tus errores guardados.',privacyEyebrow:'PRIVACIDAD DEL MICRÓFONO',consentTitle:'Antes de iniciar el reconocimiento de voz',consentBody:'El servicio de reconocimiento de voz de tu navegador puede procesar el audio del micrófono para generar texto. English Twin no guarda audio sin procesar de Guided Speech. El texto reconocido, la puntuación de precisión y los errores de aprendizaje pueden guardarse en tu cuenta para la práctica adaptativa.',notNow:'Ahora no',acceptStart:'Entiendo · Empezar',hearTarget:'Escuchar frase',reset:'Reiniciar',speakNow:'Hablar ahora',listening:'Escuchando…',heard:'LO QUE OÍMOS',accuracy:'PRECISIÓN ORAL',excellent:'Coincidencia excelente',good:'Bien — una repetición clara más',retry:'Intentar de nuevo',missing:'Faltante / poco claro',extra:'Palabras adicionales detectadas',nextDrill:'Siguiente ejercicio',freeConversation:'CONVERSACIÓN LIBRE',readyNatural:'¿Listo para hablar con naturalidad?',liveBody:'La conversación en directo utiliza tu sesión de voz autenticada de English Twin para un diálogo abierto.',openLive:'Abrir Live'},
};
