import { useEffect, useRef, useState } from 'react';
import { Navigate, useNavigate } from 'react-router-dom';
import { onAuthStateChanged, User } from 'firebase/auth';
import { addDoc, collection, doc, getDoc, serverTimestamp } from 'firebase/firestore';
import { ArrowLeft, Mic, Radio, Square, Volume2 } from 'lucide-react';
import AppDock from './AppDock';
import { auth, db } from './firebase';
import { directionFor, normalizeLanguage } from './languageSupport';
import { liveVoiceSupportCopy } from './liveVoiceSupportCopy';

type VoiceState = 'READY' | 'CONNECTING' | 'LISTENING' | 'AI_SPEAKING' | 'ERROR';
type TranscriptItem = { role: 'learner' | 'twin'; text: string };
type AudioRuntime = { inputContext: AudioContext; outputContext: AudioContext; stream: MediaStream; source: MediaStreamAudioSourceNode; processor: ScriptProcessorNode };
const LIVE_MODEL = 'gemini-3.1-flash-live-preview';
const CONSENT_KEY = 'english-twin-voice-consent-v1';
function bytesToBase64(bytes: Uint8Array) { let binary=''; for(let i=0;i<bytes.length;i+=0x8000) binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000)); return btoa(binary); }
function base64ToBytes(value:string){const binary=atob(value);const bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return bytes;}
function downsample(buffer:Float32Array,sourceRate:number,targetRate:number){if(targetRate>=sourceRate)return buffer;const ratio=sourceRate/targetRate,length=Math.round(buffer.length/ratio),result=new Float32Array(length);let sourceOffset=0;for(let i=0;i<length;i++){const nextOffset=Math.round((i+1)*ratio);let sum=0,count=0;for(let j=sourceOffset;j<nextOffset&&j<buffer.length;j++){sum+=buffer[j];count++;}result[i]=count?sum/count:0;sourceOffset=nextOffset;}return result;}
function floatToPcm16(buffer:Float32Array){const pcm=new Int16Array(buffer.length);for(let i=0;i<buffer.length;i++){const sample=Math.max(-1,Math.min(1,buffer[i]));pcm[i]=sample<0?sample*0x8000:sample*0x7fff;}return new Uint8Array(pcm.buffer);}

export default function VoiceLab(){
 const nav=useNavigate(); const [user,setUser]=useState<User|null>(null); const [profile,setProfile]=useState<Record<string,any>>({}); const [loading,setLoading]=useState(true); const [state,setState]=useState<VoiceState>('READY'); const [error,setError]=useState(''); const [transcript,setTranscript]=useState<TranscriptItem[]>([]); const [inputDraft,setInputDraft]=useState(''); const [outputDraft,setOutputDraft]=useState(''); const [voiceConsent,setVoiceConsent]=useState(()=>localStorage.getItem(CONSENT_KEY)==='accepted'); const [showConsent,setShowConsent]=useState(false);
 const wsRef=useRef<WebSocket|null>(null),audioRef=useRef<AudioRuntime|null>(null),nextPlayTimeRef=useRef(0),startedAtRef=useRef<number|null>(null),transcriptRef=useRef<TranscriptItem[]>([]),inputDraftRef=useRef(''),outputDraftRef=useRef(''),stateRef=useRef<VoiceState>('READY');
 const applyState=(next:VoiceState)=>{stateRef.current=next;setState(next)}; const applyInputDraft=(next:string)=>{inputDraftRef.current=next;setInputDraft(next)}; const applyOutputDraft=(next:string)=>{outputDraftRef.current=next;setOutputDraft(next)};
 useEffect(()=>onAuthStateChanged(auth,async current=>{setUser(current);if(!current){setProfile({});setLoading(false);return}try{const snap=await getDoc(doc(db,'users',current.uid));setProfile(snap.exists()?snap.data():{})}finally{setLoading(false)}}),[]); useEffect(()=>{transcriptRef.current=transcript},[transcript]); useEffect(()=>()=>{void teardown(false)},[]);
 const language=normalizeLanguage(profile.explanationLanguage||profile.nativeLanguage||profile.interfaceLanguage||'English'),copy=liveVoiceSupportCopy[language],dir=directionFor(language);
 if(loading)return <div className="app-shell" dir={dir}><div className="phone"><main className="page"><Radio/><p>{copy.loading}</p></main><AppDock language={language}/></div></div>; if(!user)return <Navigate to="/welcome" replace/>;
 function pushTranscript(role:'learner'|'twin',text:string){const clean=text.trim();if(clean)setTranscript(current=>[...current,{role,text:clean}]);}
 function acceptConsent(){localStorage.setItem(CONSENT_KEY,'accepted');setVoiceConsent(true);setShowConsent(false);void start(true);}
 async function playPcm(base64:string){const runtime=audioRef.current;if(!runtime)return;const bytes=base64ToBytes(base64),length=Math.floor(bytes.byteLength/2),view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),audioBuffer=runtime.outputContext.createBuffer(1,length,24000),channel=audioBuffer.getChannelData(0);for(let i=0;i<length;i++)channel[i]=view.getInt16(i*2,true)/32768;const source=runtime.outputContext.createBufferSource();source.buffer=audioBuffer;source.connect(runtime.outputContext.destination);const now=runtime.outputContext.currentTime,startAt=Math.max(now+0.02,nextPlayTimeRef.current||now);source.start(startAt);nextPlayTimeRef.current=startAt+audioBuffer.duration;}
 async function handleServerMessage(event:MessageEvent){const raw=event.data instanceof Blob?await event.data.text():event.data instanceof ArrayBuffer?new TextDecoder().decode(event.data):String(event.data);let data:any;try{data=JSON.parse(raw)}catch{return}if(data.setupComplete){applyState('LISTENING');return}const content=data.serverContent;if(!content)return;if(content.inputTranscription?.text){applyInputDraft(`${inputDraftRef.current}${content.inputTranscription.text}`)}if(content.outputTranscription?.text){applyOutputDraft(`${outputDraftRef.current}${content.outputTranscription.text}`)}for(const part of content.modelTurn?.parts||[]){if(part.inlineData?.data){applyState('AI_SPEAKING');await playPcm(part.inlineData.data)}}if(content.turnComplete){if(inputDraftRef.current){pushTranscript('learner',inputDraftRef.current);applyInputDraft('')}if(outputDraftRef.current){pushTranscript('twin',outputDraftRef.current);applyOutputDraft('')}applyState('LISTENING')}if(content.interrupted){nextPlayTimeRef.current=0;applyState('LISTENING')}}
 async function createAudioRuntime(ws:WebSocket){const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false}),inputContext=new AudioContext(),outputContext=new AudioContext();await Promise.all([inputContext.resume(),outputContext.resume()]);const source=inputContext.createMediaStreamSource(stream),processor=inputContext.createScriptProcessor(4096,1,1),silentGain=inputContext.createGain();silentGain.gain.value=0;source.connect(processor);processor.connect(silentGain);silentGain.connect(inputContext.destination);processor.onaudioprocess=event=>{if(ws.readyState!==WebSocket.OPEN||stateRef.current==='CONNECTING')return;const pcm=floatToPcm16(downsample(event.inputBuffer.getChannelData(0),inputContext.sampleRate,16000));ws.send(JSON.stringify({realtimeInput:{audio:{mimeType:'audio/pcm;rate=16000',data:bytesToBase64(pcm)}}}))};audioRef.current={inputContext,outputContext,stream,source,processor};}
 async function start(consentOverride=false){if(!voiceConsent&&!consentOverride){setShowConsent(true);return}if(!user||(stateRef.current!=='READY'&&stateRef.current!=='ERROR'))return;setError('');setTranscript([]);applyInputDraft('');applyOutputDraft('');applyState('CONNECTING');try{if(!navigator.mediaDevices?.getUserMedia)throw new Error(copy.micUnavailable);const idToken=await user.getIdToken(),tokenResponse=await fetch('/api/live-token',{method:'POST',headers:{Authorization:`Bearer ${idToken}`}}),tokenPayload=await tokenResponse.json();if(!tokenResponse.ok||!tokenPayload?.token)throw new Error(copy.sessionCreate);const ws=new WebSocket(`wss://generativelanguage.googleapis.com/ws/google.ai.generativelanguage.v1beta.GenerativeService.BidiGenerateContentConstrained?access_token=${encodeURIComponent(tokenPayload.token)}`);wsRef.current=ws;ws.onmessage=event=>{void handleServerMessage(event)};ws.onerror=()=>{setError(copy.connectionError);applyState('ERROR')};ws.onclose=event=>{if(event.code!==1000&&stateRef.current!=='READY')setError(copy.sessionClosed);if(stateRef.current!=='READY')applyState('READY')};ws.onopen=async()=>{try{ws.send(JSON.stringify({setup:{model:`models/${tokenPayload.model||LIVE_MODEL}`,generationConfig:{responseModalities:['AUDIO'],speechConfig:{voiceConfig:{prebuiltVoiceConfig:{voiceName:'Kore'}}}},systemInstruction:{parts:[{text:'You are English Twin, a patient English speaking coach. Keep the conversation in English, adapt to the learner, ask one natural question at a time, and gently recast meaningful errors without interrupting fluency.'}]},inputAudioTranscription:{},outputAudioTranscription:{}}}));await createAudioRuntime(ws);startedAtRef.current=Date.now()}catch{setError(copy.micStartError);applyState('ERROR');void teardown(false)}}}catch{setError(copy.sessionStartError);applyState('ERROR')}}
 async function teardown(saveSession=true){const runtime=audioRef.current;audioRef.current=null;if(runtime){runtime.processor.onaudioprocess=null;try{runtime.processor.disconnect()}catch{}try{runtime.source.disconnect()}catch{}runtime.stream.getTracks().forEach(track=>track.stop());await Promise.allSettled([runtime.inputContext.close(),runtime.outputContext.close()])}const ws=wsRef.current;wsRef.current=null;if(ws&&ws.readyState<WebSocket.CLOSING)ws.close(1000,'session ended');nextPlayTimeRef.current=0;const startedAt=startedAtRef.current;startedAtRef.current=null;const items=transcriptRef.current;if(saveSession&&user&&startedAt&&items.length){try{await addDoc(collection(db,'users',user.uid,'learningSessions'),{type:'speaking-live',model:LIVE_MODEL,startedAtMs:startedAt,durationSeconds:Math.max(1,Math.round((Date.now()-startedAt)/1000)),transcript:items,createdAt:serverTimestamp()})}catch{}}applyInputDraft('');applyOutputDraft('');applyState('READY')}
 const active=state==='CONNECTING'||state==='LISTENING'||state==='AI_SPEAKING';
 const stateTitle=state==='READY'?copy.ready:state==='CONNECTING'?copy.connecting:state==='LISTENING'?copy.listening:state==='AI_SPEAKING'?copy.speaking:copy.attention;
 return <div className="app-shell" dir={dir}><div className="phone"><main className="page voice-live"><button className="back" onClick={()=>nav('/')}><ArrowLeft/> {copy.home}</button><header><span className="eyebrow">{copy.eyebrow}</span><h1>{copy.title}</h1><p>{copy.intro}</p></header>{showConsent&&<section className="rich-activity-card" role="dialog" aria-modal="true" aria-labelledby="voice-consent-title"><div className="section-heading"><span>{copy.privacy}</span><h3 id="voice-consent-title">{copy.consentTitle}</h3></div><p>{copy.consentBody}</p><div className="lesson-actions"><button className="ghost" onClick={()=>setShowConsent(false)}>{copy.notNow}</button><button className="primary lime" onClick={acceptConsent}>{copy.acceptStart}</button></div></section>}<section className={`voice-stage ${state.toLowerCase()}`}><div className="voice-pulse"><Mic/></div><span className="status-dot">{state}</span><h2>{stateTitle}</h2><p>{state==='READY'?copy.readyHint:copy.activeHint}</p><button className={active?'voice-stop':'primary lime'} onClick={()=>active?void teardown(true):void start()}>{active?<><Square/> {copy.end}</>:<><Mic/> {copy.start}</>}</button></section>{error&&<p className="error">{error}</p>}<section><div className="section-heading"><span>{copy.transcript}</span><h3>{copy.evidence}</h3></div>{!transcript.length&&!inputDraft&&!outputDraft?<div className="signal-empty"><Volume2/><div><b>{copy.emptyTitle}</b><p>{copy.emptyBody}</p></div></div>:<div className="voice-transcript">{transcript.map((item,index)=><article className={item.role} key={`${item.role}-${index}`}><span>{item.role==='learner'?copy.you:copy.twin}</span><p>{item.text}</p></article>)}{inputDraft&&<article className="learner partial"><span>{copy.you}</span><p>{inputDraft}</p></article>}{outputDraft&&<article className="twin partial"><span>{copy.twin}</span><p>{outputDraft}</p></article>}</div>}</section></main><AppDock language={language}/></div></div>;
}
